### ISSUE TITLE
Something went wrong. Please try after sometime error when click cancel and logout button on Guest Information page 

### ISSUE THREAD

**Issue by neerajkhatri-btc** [NishantUpadhyay-BTC/BLISS-Issue-Tracking#1]
![selection_048](https://cloud.githubusercontent.com/assets/16792762/12917761/503a2ace-cf61-11e5-9915-104118c32443.png)

Step 1: login id and password
Step 2: enter data in Personal Retreat Availability page and click check availability.

Step 3: reserve any lodging.
Step 4: in Guest Information page click cancel and logout button

**Comment by NishantUpadhyay-BTC** [comment]
@neerajkhatri-btc I have fixed this issue. Please look into this

**Comment by neerajkhatri-btc** [comment]
yes.this is close
