### ISSUE TITLE
unable to work. Reservation>payment>New Payment>purchase in office UI

### ISSUE THREAD

**Issue by neerajkhatri-btc** [NishantUpadhyay-BTC/BLISS-Issue-Tracking#10]
![selection_058](https://cloud.githubusercontent.com/assets/16792762/13041928/bf4a48f2-d3e1-11e5-8016-00f440727c06.png)

**Comment by NishantUpadhyay-BTC** [comment]
@neerajkhatri-btc  This issue is fixed. Please confirm

**Comment by neerajkhatri-btc** [comment]
that is fixed
