### ISSUE TITLE
Need to be able to confirm a reservation without Lodging

### ISSUE THREAD

**Issue by NishantUpadhyay-BTC** [NishantUpadhyay-BTC/BLISS-Issue-Tracking#104]
It came up in testing that we are no longer able to confirm a reservation without any lodging. We need to be able to do this. For example, when we book a staff guest (staying with a staff member) into an event.

**Comment by NishantUpadhyay-BTC** [comment]
Steps to reproduce this issue
- Go to Event Tab
- Create new Event 
- Do some detailed blocking for 2 or 3 cabins
- Go to reservation tab
- Search or create user
- Set reservation for that event for this current user
- Go to details screen
- Set staff as guest type
- Go to confirm screen
- User should be able to confirm reservation without select any lodging

**Comment by neerajkhatri-btc** [comment]
@NishantUpadhyay-BTC : this issue is fixed.
