### ISSUE TITLE
UI issue in flash message

### ISSUE THREAD

**Issue by neerajkhatri-btc** [NishantUpadhyay-BTC/BLISS-Issue-Tracking#109]
![selection_173](https://cloud.githubusercontent.com/assets/16792762/14073096/ca9b16dc-f4e3-11e5-8f87-35a6042f5da2.png)

**Comment by neerajkhatri-btc** [comment]
@NishantUpadhyay-BTC : Remove circle from left.

**Comment by amitpatelx** [comment]
That is default style of `li` element, I suppose. That should be removed.

**Comment by neerajkhatri-btc** [comment]
@NishantUpadhyay-BTC : this issue is fixed.

**Comment by neerajkhatri-btc** [comment]
@NishantUpadhyay-BTC : this issue is fixed.
