### ISSUE TITLE
flash message remove 'No route matches "https://mandala.breitenbush.com:10443/guests/reset_password"' after Sign in

### ISSUE THREAD

**Issue by neerajkhatri-btc** [NishantUpadhyay-BTC/BLISS-Issue-Tracking#11]
![selection_059](https://cloud.githubusercontent.com/assets/16792762/13107812/829073b8-d595-11e5-9aab-3584a06a0463.png)

Step 1. Click forgot password
Step 2. Click reset password button without enter e-mail
Step 3. Enter valid e-mail(neeraj.khatri@botreetechnologies.com) and password(OCGXSPUQ) and click sign in button.

**Comment by NishantUpadhyay-BTC** [comment]
@neerajkhatri-btc Please test this. This is deployed.

**Comment by neerajkhatri-btc** [comment]
@NishantUpadhyay-BTC : Still issue in there

**Comment by NishantUpadhyay-BTC** [comment]
@neerajkhatri-btc  This is fixed,Please test

**Comment by neerajkhatri-btc** [comment]
@NishantUpadhyay-BTC : This is Fixed.
