### ISSUE TITLE
Guest Information: UI issue in 'Frequently Asked Questions' on mouse hover

### ISSUE THREAD

**Issue by neerajkhatri-btc** [NishantUpadhyay-BTC/BLISS-Issue-Tracking#111]
![selection_177](https://cloud.githubusercontent.com/assets/16792762/14103367/6b14f5f4-f5bd-11e5-82e9-d332def00db4.png)

**Comment by amitpatelx** [comment]
@neerajkhatri-btc you need to add more details what is the issue and what is expected behaviour.

**Comment by neerajkhatri-btc** [comment]
@AmitPatel-BoTreeConsulting : mouse hover on 'Frequently Asked Questions' so expected behavior is normal not going to white

**Comment by neerajkhatri-btc** [comment]
@NishantUpadhyay-BTC : this issue is fixed.
