### ISSUE TITLE
Availability issue.

### ISSUE THREAD

**Issue by HirenBhalani** [NishantUpadhyay-BTC/BLISS-Issue-Tracking#113]
- [x] Date: 31/03/2016, nights: 1, people: 1, 3 gender available one for female and two for male, but while search from guest_ui.
- [x] same for 4/04/2016
- [x] Date: 19/04/2014, nights: 3, people: 1, tent, pv and tent site are not available, but still it's showing in guest_ui
- [x]

**Comment by HirenBhalani** [comment]
- [x] showing wrong cabins, but When I click on reserve IT's redirecting me to root_path Is this right flow?

**Comment by NishantUpadhyay-BTC** [comment]
It means, redirecting part works well but showing wrong cabin is wrong.

**Comment by HirenBhalani** [comment]
start date not stored in session.

**Comment by HirenBhalani** [comment]
I think when I select reserved cabin it should not redirect me to rootpath but show message on same page and should remove table from bottom.

**Comment by NishantUpadhyay-BTC** [comment]
Actually, till now, reserved cabin was not displaying in check availability but now if you have such case then we have to handle it the way you are telling.

**Comment by HirenBhalani** [comment]
![welcome to breitenbush](https://cloud.githubusercontent.com/assets/8123588/14167700/ab1175e6-f73a-11e5-88fe-e04eebf35cad.png)

**Comment by NishantUpadhyay-BTC** [comment]
@HirenBhalani-BTC  If you have tested then please close this issue and add list of working cases to here so that I can send email to Paul.

**Comment by NishantUpadhyay-BTC** [comment]
Logic behind the availability check is changed so that we can close this for now and we will create new issue if new use cases get failed. So I am closing this for now.
