### ISSUE TITLE
Wrong displaying lodging list

### ISSUE THREAD

**Issue by neerajkhatri-btc** [NishantUpadhyay-BTC/BLISS-Issue-Tracking#114]
**Office UI**

Step 1. login in Office UI
Step 2. reservations tab > Search guest > NISHANT Pandya > New Personal Retreat
Step 3. Select July 31 > Guest Count > People = 3 and Nights = 6  
Step 4. Go to Tents Tab > TENT SITE available 
Step 5. It should be available

**Guest UI**
Step 1. enter arrival date Sunday, July 31, 2016
Step 2. NUMBER OF NIGHTS = 6
Step 3. GUESTS (INCLUDING CHILDREN) = 3
Step 4. MINIMUM NUMBER OF BEDS NEEDED = 3
Step 5. click check availability button

![selection_180](https://cloud.githubusercontent.com/assets/16792762/14198671/84433e34-f7fa-11e5-925a-20c270790df0.png)

**Comment by NishantUpadhyay-BTC** [comment]
@neerajkhatri-btc  There are many changes in availability check logic so for now I am closing this issue because logic behind it , is changed.
