### ISSUE TITLE
In Current office UI, I can see two users having same primary e-mail ID.

### ISSUE THREAD

**Issue by neerajkhatri-btc** [NishantUpadhyay-BTC/BLISS-Issue-Tracking#116]
@NishantUpadhyay-BTC : IS that possible?

**Comment by NishantUpadhyay-BTC** [comment]
@neerajkhatri-btc  Yes, This is something new and we are working on it. Till now, in office UI, we retrive entity from user and not user from entity and email id is not uniq so there is possibility that email ids are common among users already exists on office UI. I am going to ask Paul for this and then get back to you. Till that we can put  this on hold.
