### ISSUE TITLE
In Payment Summary Zip code accepted character

### ISSUE THREAD

**Issue by neerajkhatri-btc** [NishantUpadhyay-BTC/BLISS-Issue-Tracking#12]
![selection_060](https://cloud.githubusercontent.com/assets/16792762/13145025/03ce551a-d674-11e5-84d8-ecdaa9395d55.png)
![selection_061](https://cloud.githubusercontent.com/assets/16792762/13145026/03d08ee8-d674-11e5-890f-0fb5011089df.png)

**Comment by NishantUpadhyay-BTC** [comment]
@neerajkhatri-btc this issue is fixed and deployed.

**Comment by neerajkhatri-btc** [comment]
@NishantUpadhyay-BTC : this issue is fixed
