### ISSUE TITLE
 Guest UI: "Home" button function

### ISSUE THREAD

**Issue by NishantUpadhyay-BTC** [NishantUpadhyay-BTC/BLISS-Issue-Tracking#120]
Home button should take us to the to last page visited of the reservation in progress. If no reservation in progress, take us to the Availability Screen. In the future, this will take us to a list of all current and past reservations for that guest - but that is a future implementation.

**Comment by NishantUpadhyay-BTC** [comment]
@neerajkhatri-btc For now, Home button is removed as per Paul's suggestion. So I have changed accordingly. Please verify on staging.

**Comment by neerajkhatri-btc** [comment]
@NishantUpadhyay-BTC : fixed.
