### ISSUE TITLE
Guest UI: Thank you page: Use BLISS receipt number instead of Transaction number

### ISSUE THREAD

**Issue by NishantUpadhyay-BTC** [NishantUpadhyay-BTC/BLISS-Issue-Tracking#123]
On the Thank You page, please display the Receipt Number from BLISS (and label it "Receipt Number"). When searching for transactions in BLISS, we cannot use the Transaction number - only the receipt number, so this is the more useful data to have if a guest wants us to search for a transaction.

**Comment by HirenBhalani** [comment]
http://stackoverflow.com/questions/36568628/receipt-id-is-null-in-paypal-response-how-can-i-get-it

**Comment by neerajkhatri-btc** [comment]
@NishantUpadhyay-BTC : this issue is fixed.
