### ISSUE TITLE
 Guest UI: Thank you page: print - coding gobbledeygook 

### ISSUE THREAD

**Issue by NishantUpadhyay-BTC** [NishantUpadhyay-BTC/BLISS-Issue-Tracking#125]
Printing creates html gibberish at the top of page

**Comment by neerajkhatri-btc** [comment]
@NishantUpadhyay-BTC : pls check that

![selection_190](https://cloud.githubusercontent.com/assets/16792762/14376815/68409d50-fd89-11e5-9a5a-d726857838f2.png)
![selection_191](https://cloud.githubusercontent.com/assets/16792762/14376816/6841a3b2-fd89-11e5-9751-4d87d3f9e0b2.png)

**Comment by neerajkhatri-btc** [comment]
@NishantUpadhyay-BTC : this issue is fixed.
