### ISSUE TITLE
 Guest UI: Thank you page: Speical Diet? 

### ISSUE THREAD

**Issue by NishantUpadhyay-BTC** [NishantUpadhyay-BTC/BLISS-Issue-Tracking#126]
Made a reservation for one person one night, on the Thank you page, meals were listed as Special Diet - but did not choose SD. However, the reservation listed in the Office UI did not indicate Special Diet.

**Comment by neerajkhatri-btc** [comment]
@HirenBhalani-BTC : this issue is fixed.
