### ISSUE TITLE
#1261 Guest UI: Verify all dollar amounts round to two decimal places 

### ISSUE THREAD

**Issue by NishantUpadhyay-BTC** [NishantUpadhyay-BTC/BLISS-Issue-Tracking#127]
Check whole site: all dollar figures should round to two decimals. Format = $123.00. We noticed this on the Thank You page: "We've taken a payment of" looks like $123.0

**Comment by neerajkhatri-btc** [comment]
@NishantUpadhyay-BTC : this issue is fixed.
