### ISSUE TITLE
In forgot password page see reset password button show wrong tool tip "Sign in"

### ISSUE THREAD

**Issue by neerajkhatri-btc** [NishantUpadhyay-BTC/BLISS-Issue-Tracking#13]
![selection_069](https://cloud.githubusercontent.com/assets/16792762/13145198/285995d8-d675-11e5-8084-135bb98da649.png)

**Comment by NishantUpadhyay-BTC** [comment]
@neerajkhatri-btc  This issue is fixed. Please test again.

**Comment by neerajkhatri-btc** [comment]
@NishantUpadhyay-BTC : This issue is fixed
