### ISSUE TITLE
#1253 Guest UI: Notice after sucessful login - language change 

### ISSUE THREAD

**Issue by NishantUpadhyay-BTC** [NishantUpadhyay-BTC/BLISS-Issue-Tracking#132]
Change Login Successfully to Login Successful

**Comment by neerajkhatri-btc** [comment]
@NishantUpadhyay-BTC : pls suggest me where i have to test this change? 
Can u pls give me exact scenario?

**Comment by neerajkhatri-btc** [comment]
@NishantUpadhyay-BTC : this issue is fixed.
