### ISSUE TITLE
 Guest UI: Phone Number Formatting 

### ISSUE THREAD

**Issue by NishantUpadhyay-BTC** [NishantUpadhyay-BTC/BLISS-Issue-Tracking#134]
On confirm info page (after sucessful login)- cannot check or uncheck �Use as Preferred� when entering a new number because the field would not accept format. If we don�t present the required format then fields must be smart enough to parse this out automatically. We'd prefer to both display the required format AND have the field auto-parse data if it's entered incorrectly.

**Comment by NishantUpadhyay-BTC** [comment]
We have to address this two points in this issue:
Please enter new format 555.555.5555
However - how shall we handle non-US numbers?

**Comment by HirenBhalani** [comment]
To handle non US number, we have to mention country code with number, which is starting with `+` , means we have to change current regex.

For validation regex refrence cleck [here](http://stackoverflow.com/a/6967885).

**Comment by neerajkhatri-btc** [comment]
@HirenBhalani-BTC : pls fix this

Step 1. login id and password
Step 2. click user profile and enter number in HOME PHONE : 111.111.5555

![selection_249](https://cloud.githubusercontent.com/assets/16792762/14732865/0a0b6c8a-087c-11e6-9d52-4576fe835b39.png)

**Comment by neerajkhatri-btc** [comment]
@NishantUpadhyay-BTC : this issue is fixed.
