### ISSUE TITLE
#1251 Guest UI: Consecutive Availability Notice: Remove extra comma 

### ISSUE THREAD

**Issue by NishantUpadhyay-BTC** [NishantUpadhyay-BTC/BLISS-Issue-Tracking#135]
Current text: "A Reservation for a lodging of this type might be possible but, would require a move that this system cannot yet accommodate. If you would like to try booking this lodging, please call our Reservations Office at 503.854.3320" -Please remove the comma after "but"

**Comment by neerajkhatri-btc** [comment]
@NishantUpadhyay-BTC : this issue is fixed.
