### ISSUE TITLE
Guest UI: Availability Screen: check reduction in mobile on actual device. No shadows ?

### ISSUE THREAD

**Issue by NishantUpadhyay-BTC** [NishantUpadhyay-BTC/BLISS-Issue-Tracking#136]
We need to check how the Availability Screen is presenting on an actual mobile device. When reduced in desktop browswers, Lodge availabiilty is getting tucked under others. Also no shadows are showing up

**Comment by neerajkhatri-btc** [comment]
@HirenBhalani-BTC : this issue is fixed.
