### ISSUE TITLE
Make proper Tool tip

### ISSUE THREAD

**Issue by neerajkhatri-btc** [NishantUpadhyay-BTC/BLISS-Issue-Tracking#14]
![selection_067](https://cloud.githubusercontent.com/assets/16792762/13145109/73b0663e-d674-11e5-87b7-de3ae7bd38dc.png)
![selection_068](https://cloud.githubusercontent.com/assets/16792762/13145110/73b3f4c0-d674-11e5-986f-eccbb96a2bb6.png)

**Comment by NishantUpadhyay-BTC** [comment]
@neerajkhatri-btc  I have deployed this. Please have a look

**Comment by neerajkhatri-btc** [comment]
@NishantUpadhyay-BTC : this issue fix now
