### ISSUE TITLE
 Guest UI: Global: Date Format: 

### ISSUE THREAD

**Issue by NishantUpadhyay-BTC** [NishantUpadhyay-BTC/BLISS-Issue-Tracking#140]
Please format all dates in the UI (including the Availability Table) to conform to the following: where day names are used, please abbreviate (e.g. Mon, Tue, Wed, Thu, Fri, Sat, Sun). Dates should be in the format MM-DD-YY - though please do not use leading zeros. Example: Fri, 4-15-16

**Comment by neerajkhatri-btc** [comment]
@NishantUpadhyay-BTC : this issue is fixed.
