### ISSUE TITLE
 Guest UI: Personal Retreat Availability:Willing to Share: Help: 

### ISSUE THREAD

**Issue by NishantUpadhyay-BTC** [NishantUpadhyay-BTC/BLISS-Issue-Tracking#146]
Please change the text for this help note to be: "If you are booking a cabin alone, you can expect to share with one other person of the same gender. You can indicate your willingness to share or choose Guaranteed Privacy (GP). The rates for GP are doubled, except for mid-week during the non-peak season, when GP costs an additional $45/night."

**Comment by neerajkhatri-btc** [comment]
@NishantUpadhyay-BTC : this issue is fixed.
