### ISSUE TITLE
In minimum number of beds needed for your party include drop down in "Please Select " 

### ISSUE THREAD

**Issue by neerajkhatri-btc** [NishantUpadhyay-BTC/BLISS-Issue-Tracking#15]
![selection_064](https://cloud.githubusercontent.com/assets/16792762/13144988/cdb808f4-d673-11e5-96b3-1527f4d08775.png)

**Comment by NishantUpadhyay-BTC** [comment]
@neerajkhatri-btc Please test this. It is deployed

**Comment by neerajkhatri-btc** [comment]
@NishantUpadhyay-BTC : this issue fix now
