### ISSUE TITLE
 Guest UI: Availability: Lodgings List: Lodging Details Pop-up: Incorrect Rates 

### ISSUE THREAD

**Issue by NishantUpadhyay-BTC** [NishantUpadhyay-BTC/BLISS-Issue-Tracking#150]
Displayed rates are incorrect. Are we pulling these from the rate table? Some are swapped, others (e.g. children) are just plain wrong.

**Comment by neerajkhatri-btc** [comment]
@NishantUpadhyay-BTC : this issue is fixed.
