### ISSUE TITLE
 Guest UI: Guest Details: Linens Help 

### ISSUE THREAD

**Issue by NishantUpadhyay-BTC** [NishantUpadhyay-BTC/BLISS-Issue-Tracking#152]
Please change the help text to read: "All Breitenbush beds include a fitted bottom sheet. Guests are expected to _bring their own linens (top sheet, blanket/sleeping bag, pillows and towels). If you would like Breitenbush to provide these, please indicate how many sets you require. "Individual Sets" (designed for one person in a bed) include a top sheet, two blankets, one pillow and two towels. "Couple Sets" (designed for two people sharing a bed) include a top sheet, two blankets, two pillows and four towels. " _

**Comment by neerajkhatri-btc** [comment]
@NishantUpadhyay-BTC : this issue is fixed.
