### ISSUE TITLE
 Guest UI: Reservation Summary/Thank You: Meals Language Change 

### ISSUE THREAD

**Issue by NishantUpadhyay-BTC** [NishantUpadhyay-BTC/BLISS-Issue-Tracking#157]
On both the Reservations Summary and Thank You page, please change the language for "Special Diet" meals to: "<#> Guest is [are] eating special diet meals". Examples: "1 Guest is eating special diet meals", "2 Guests are eating special diet meals".

**Comment by neerajkhatri-btc** [comment]
@NishantUpadhyay-BTC : this issue is fixed.
