### ISSUE TITLE
In login page flash message is required to entering without e-mail id or password

### ISSUE THREAD

**Issue by neerajkhatri-btc** [NishantUpadhyay-BTC/BLISS-Issue-Tracking#16]
Step 1. enter data in Personal Retreat Availability page and click check availability button
Step 2. Select any lodging and reserve button click

![selection_065](https://cloud.githubusercontent.com/assets/16792762/13145240/58adc970-d675-11e5-823e-e8287791e10a.png)

Step 3. in login page enter without e-mail id or without password

**Comment by NishantUpadhyay-BTC** [comment]
@neerajkhatri-btc Please test this. It is fixed.

**Comment by neerajkhatri-btc** [comment]
@NishantUpadhyay-BTC : it is fixed
