### ISSUE TITLE
 Guest UI: Cancellation Policy: 7-Day Language Changes 

### ISSUE THREAD

**Issue by NishantUpadhyay-BTC** [NishantUpadhyay-BTC/BLISS-Issue-Tracking#160]
For both deposit only and full payment canellation policy messages, Please change "non refundable eposit" to "non-refundable deposit" - and change the wording for the seven day policy, starting from" Because" � replace with: "Your reservation is within our 7-day cancellation period. If you have to cancel this reservation your deposit will be forfeit, but do call us right away if an emergency comes up."

**Comment by neerajkhatri-btc** [comment]
@NishantUpadhyay-BTC : this issue is fixed.
