### ISSUE TITLE
 Guest UI: Office UI: Add field "Reservation Notes from the Guest" 

### ISSUE THREAD

**Issue by NishantUpadhyay-BTC** [NishantUpadhyay-BTC/BLISS-Issue-Tracking#162]
Please change the label of the field "Reservation Notes" on the Details tab to be "Reservation Notes from the Office Team", and also add a non-editable field "Reservation Notes from the Guest " on the Details tab in the area under EA/SO. Notes entered by the guest in the Notes field of the Guest UI should appear here. These notes should display just as the current notes field displays in the "Web Reservations" section of the Home Page, and will replace these notes for that reservations that display in that section only. However, we�ll need to reference the notes WE made (the "Reservation Notes from the Office Team" field) when this reservation appears in any other lists. Example: Guest makes a reservation in the Guest UI and adds notes to the notes field on the Guest Details page. After completing payment for their reservation, this reservation appears in the "Web Reservations" section of the Home Screen, and the notes entered by the guest appear below as an expandable link, just as the current notes do (but instead of them). Office team then edits/confirms the reservation and might make notes of their own in the "Reservation Notes from the Office Team" field. If this reservation appears in any other lists on the home screen (e.g. "Balance Due Reservations") then we should see the notes from the "Reservation Notes from the Office Team" field.

**Comment by neerajkhatri-btc** [comment]
@HirenBhalani-BTC : this issue is fixed.
