### ISSUE TITLE
 Guest UI: Print Reservation Summary: Formatting 

### ISSUE THREAD

**Issue by NishantUpadhyay-BTC** [NishantUpadhyay-BTC/BLISS-Issue-Tracking#163]
It would be nice if the appearance of the printed reservation summary could more closely match what users see on the website. So for instance - can we include the website header and footer at the top and bottom of the printed page? Also, can it be formatted such that the entire summary fits on just one 8 1/2" by 11" page?

**Comment by neerajkhatri-btc** [comment]
@NishantUpadhyay-BTC : this issue is fixed.
