### ISSUE TITLE
 Guest UI: New Account Email - Change subject line 

### ISSUE THREAD

**Issue by NishantUpadhyay-BTC** [NishantUpadhyay-BTC/BLISS-Issue-Tracking#165]
Current subject lin: "New account setup". New subject line: "New Breitenbush Account Set Up for <User First Name> <User Last Name>"

This will also aid during our testing process, as we'll be setting up about 100 new test users, and all set up emails will be forwarded to a single account for verification.

**Comment by neerajkhatri-btc** [comment]
@NishantUpadhyay-BTC : this issue is fixed.
