### ISSUE TITLE
In Guest Information page Space between label and Tool tip  

### ISSUE THREAD

**Issue by neerajkhatri-btc** [NishantUpadhyay-BTC/BLISS-Issue-Tracking#17]
![selection_066](https://cloud.githubusercontent.com/assets/16792762/13135739/848f6fe4-d639-11e5-9416-63b1ed4544d6.png)

**Comment by amitpatelx** [comment]
Let us wait for Update UI from JVM media.

**Comment by NishantUpadhyay-BTC** [comment]
@neerajkhatri-btc Please test this. It is fixed.

**Comment by neerajkhatri-btc** [comment]
@NishantUpadhyay-BTC : It is fixed.
