### ISSUE TITLE
Date picker plug in issue in arrival date selecting in Chrome 

### ISSUE THREAD

**Issue by neerajkhatri-btc** [NishantUpadhyay-BTC/BLISS-Issue-Tracking#18]
![selection_070](https://cloud.githubusercontent.com/assets/16792762/13167212/f550e416-d6f6-11e5-9355-57c3be5d1c13.png)

Step 1. Scroll page and click Date picker

**Comment by NishantUpadhyay-BTC** [comment]
@neerajkhatri-btc This is fixed. Please test.

**Comment by neerajkhatri-btc** [comment]
@NishantUpadhyay-BTC : This is fixed.

**Comment by neerajkhatri-btc** [comment]
@NishantUpadhyay-BTC : pls fix this issue

**Comment by neerajkhatri-btc** [comment]
@NishantUpadhyay-BTC : this is fixed.
