### ISSUE TITLE
check holiday and special period not working in check availability.

### ISSUE THREAD

**Issue by HirenBhalani** [NishantUpadhyay-BTC/BLISS-Issue-Tracking#180]

**Comment by NishantUpadhyay-BTC** [comment]
If  number  of  nights  is  less    than    2 for   weekends    and holiday nights  AND it  is  more    than    7   days    in  advance,    they    get a   warning message saying  something   like:   “For  weekends    and holidays,   there   is  a   two night   minimum.”     This    check   should  happen  as  soon    as  they    indicate    the arrival date    and the number  of  nights (no  matter  which   they    choose  first).     The message presented   should  have    an  acknowledgement button  that    once     clicked    closes  the message and resets  the most    recently    changed field   to  a blank value.

**Comment by neerajkhatri-btc** [comment]
@NishantUpadhyay-BTC : this issue is fixed.
