### ISSUE TITLE
Issue in login

### ISSUE THREAD

**Issue by HirenBhalani** [NishantUpadhyay-BTC/BLISS-Issue-Tracking#182]
(without login)
go to check availability
reserve cabin
it will redirect you to guests/login page.

now login form footer login form, it is redirecting user to same page.

**Comment by HirenBhalani** [comment]
change footer height and body margin bottom by javascript
after login 400px
without login 148px
remove from css

**Comment by neerajkhatri-btc** [comment]
@HirenBhalani-BTC : this issue is fixed.
