### ISSUE TITLE
UI issues

### ISSUE THREAD

**Issue by HirenBhalani** [NishantUpadhyay-BTC/BLISS-Issue-Tracking#184]
I found following issue to resolve.

(1) Cancellation Policy Popup
- Add margin-bottom on buttons for mobile screen device.

(2) User Profile Page.
- Touch is not working in text boxes for mobile device.

(3) Personal Retreat Availability (Available Lodging - Table)
- Issue found for mobile device for Rates and More Info Popup.
- Remove Scrolling in Available Lodging for Tablet Device Screen.
- Fix reserve now popup button size for mobile device.

(4) Reservation Summary
- Pay Deposition Only button Popup. Remove Extra Dollar sign with Price.
  I found $$

(5) Footer
- Apply Line Height in footer text boxes.

(6) General
- Found Shadow and Rounded corner for Text Boxes and Text Area need to fix without shadow and square corners.
- Remove Unused CSS.

(7) Payment Page
- Cursor not working in textbox in iPhone.

**Comment by neerajkhatri-btc** [comment]
@HirenBhalani-BTC : pls check Point 3 is not fixed.

(3) Personal Retreat Availability (Available Lodging - Table)
- Issue found for mobile device for Rates and More Info Popup.
- Remove Scrolling in Available Lodging for Tablet Device Screen.
- Fix reserve now popup button size for mobile device.

**Comment by neerajkhatri-btc** [comment]
@HirenBhalani-BTC : pls check Point 3.1 is not fixed.

Issue found for mobile device(I-Phone and I-Pad) for Rates and More Info Popup > click close button and   Reserve now button not working .

**Comment by neerajkhatri-btc** [comment]
@HirenBhalani-BTC : pls check Point 5 is not fixed.

(5) Footer cuts on > reservation summary page
     - Reservaton Summary > Current line was not in center pls do it center

**Comment by neerajkhatri-btc** [comment]
@NishantUpadhyay-BTC : pls check that

on Guest Information > click back button > on AVAILABLE LODGING > Click Reserve now button

![img_3852](https://cloud.githubusercontent.com/assets/16792762/14845079/93b12f6e-0c79-11e6-8fdc-7cd13fe4bf86.PNG)

**Comment by neerajkhatri-btc** [comment]
@NishantUpadhyay-BTC : pls check that

Thank you page > MEALS

![img_3853](https://cloud.githubusercontent.com/assets/16792762/14851242/401c3db2-0c9c-11e6-8edb-68e643cfc592.PNG)

**Comment by neerajkhatri-btc** [comment]
@NishantUpadhyay-BTC : pls check that
1. Payment Summary > Expiration > Still Cursor Show

![img_3856](https://cloud.githubusercontent.com/assets/16792762/14854346/095206c0-0cad-11e6-87d7-12a8258c7cfa.PNG)

**Comment by neerajkhatri-btc** [comment]
NishantUpadhyay-BTC : pls check that
1. On Thank You Page > Payment Details > Transaction Id

![img_3860](https://cloud.githubusercontent.com/assets/16792762/14909413/c9013b22-0e00-11e6-8050-09356c3e0a90.PNG)

**Comment by neerajkhatri-btc** [comment]
@NishantUpadhyay-BTC : pls check that 
1. UI issue in Thank You Page

![img_3861](https://cloud.githubusercontent.com/assets/16792762/14909515/215b5518-0e02-11e6-8829-1ca4d430ec4d.PNG)

**Comment by neerajkhatri-btc** [comment]
@NishantUpadhyay-BTC : this issue is fixed.
