### ISSUE TITLE
Wrong Date Show : AVAILABLE LODGING: Rates and more info : Peak Date

### ISSUE THREAD

**Issue by neerajkhatri-btc** [NishantUpadhyay-BTC/BLISS-Issue-Tracking#185]
Step 1. fill data in Personal Retreat Availability and click check availability

![selection_251](https://cloud.githubusercontent.com/assets/16792762/14733365/191f2744-0880-11e6-848a-1c05a885a8fe.png)

![selection_250](https://cloud.githubusercontent.com/assets/16792762/14733265/5f86e77c-087f-11e6-9523-2eb472def319.png)

**Comment by NishantUpadhyay-BTC** [comment]
@neerajkhatri-btc  This is not an issue, Peak date can be different then reservation date. So I am closing it.
