### ISSUE TITLE
known issue of 0 payment and wrong date on rate popup

### ISSUE THREAD

**Issue by HirenBhalani** [NishantUpadhyay-BTC/BLISS-Issue-Tracking#187]
![screenshot from 2016-04-22 17 40 04](https://cloud.githubusercontent.com/assets/8123588/14741121/bd8f6b28-08b1-11e6-8e7e-f937e3871205.png)
![screenshot from 2016-04-22 17 40 52](https://cloud.githubusercontent.com/assets/8123588/14741122/bdc57150-08b1-11e6-8859-733a9bb1d80a.png)

**Comment by HirenBhalani** [comment]
@neerajkhatri-btc

**Comment by NishantUpadhyay-BTC** [comment]
@neerajkhatri-btc I am not getting this issue. Please explain or close if this is old issue and fixed.

**Comment by NishantUpadhyay-BTC** [comment]
@neerajkhatri-btc As per the last discussion with Paul, Having 0.0$ to pay is not possible and it's edge case so no need to consider it. So you can close it.
