### ISSUE TITLE
JS issue in Date time picker

### ISSUE THREAD

**Issue by neerajkhatri-btc** [NishantUpadhyay-BTC/BLISS-Issue-Tracking#19]
Step 1. login with id and password
Step 2. click date time picker
Step 3. logout from bliss
Step 4. click date time picker

**Comment by NishantUpadhyay-BTC** [comment]
@neerajkhatri-btc This issue is fixed and deployed. Please test again.

**Comment by neerajkhatri-btc** [comment]
@NishantUpadhyay-BTC : This issue is fixed
