### ISSUE TITLE
Remove flash message 'Something went wrong. We are unable to complete reservation. Please contact Breitenbush Office.'

### ISSUE THREAD

**Issue by neerajkhatri-btc** [NishantUpadhyay-BTC/BLISS-Issue-Tracking#191]
1. Payment Paypal Through 
   ![selection_270](https://cloud.githubusercontent.com/assets/16792762/14851910/9ea3eb38-0ca0-11e6-8dc7-5345a7ff928d.png)

**Comment by NishantUpadhyay-BTC** [comment]
@neerajkhatri-btc I am unable to reproduce this issue. Can you please provide more accurate steps to reproduce this?

**Comment by NishantUpadhyay-BTC** [comment]
@neerajkhatri-btc I think this is because of Paypal "receiving limit exceeded" error issue. You can close it now.

**Comment by neerajkhatri-btc** [comment]
@NishantUpadhyay-BTC : this issue is fixed.

**Comment by NishantUpadhyay-BTC** [comment]
@neerajkhatri-btc  This is the way we are handling paypal exception, It will not create a payment or allow any further process. So this is expected. We can close it.
