### ISSUE TITLE
JS Issue on I- phone and I-pad

### ISSUE THREAD

**Issue by neerajkhatri-btc** [NishantUpadhyay-BTC/BLISS-Issue-Tracking#196]
1. On Guest Info Page > With out Phone Number > Click Continue > No Flash message display

![img_0120](https://cloud.githubusercontent.com/assets/16792762/14909612/5bd87a30-0e03-11e6-87cd-bc5e77365b25.PNG)

**Comment by NishantUpadhyay-BTC** [comment]
As per this link, iOS is not supporting HTML5 validations yet. http://stackoverflow.com/a/10664505/5031321 I am trying to find some other solution for it.

**Comment by neerajkhatri-btc** [comment]
@NishantUpadhyay-BTC : this issue is fixed.
