### ISSUE TITLE
UI issue in I - Phone

### ISSUE THREAD

**Issue by neerajkhatri-btc** [NishantUpadhyay-BTC/BLISS-Issue-Tracking#198]
1. On Personal Retreat Availability > behavior > Issue
2. Select Number of Nights 

![img_3899](https://cloud.githubusercontent.com/assets/16792762/14948612/f3661322-105f-11e6-882a-0f8c2a97398e.PNG)

**Comment by neerajkhatri-btc** [comment]
@NishantUpadhyay-BTC : pls check that
1. On Personal Retreat Availability > Gender > Willing to share 

![img_0002](https://cloud.githubusercontent.com/assets/16792762/15016717/2256473e-1230-11e6-8014-d5b572af8c9a.PNG)

**Comment by NishantUpadhyay-BTC** [comment]
@neerajkhatri-btc Unable to reproduce, It might be because of incomplete page loading.
