### ISSUE TITLE
error while hitting URL Directly - it should be redirected 

### ISSUE THREAD

**Issue by neerajkhatri-btc** [NishantUpadhyay-BTC/BLISS-Issue-Tracking#20]
1.Copy URL From Chrome
2.Paste URL in FireFox

Step 1
Chrome 
![selection_072](https://cloud.githubusercontent.com/assets/16792762/13209817/9c9bed3e-d94e-11e5-9ad7-5b1739a4e2ba.png)
Firefox
![selection_073](https://cloud.githubusercontent.com/assets/16792762/13209818/9c9d8b44-d94e-11e5-9f82-4ed461e5b062.png)

Step 2
Chrome 
![selection_074](https://cloud.githubusercontent.com/assets/16792762/13210677/88e806ac-d957-11e5-8e13-e0cf4eddd39a.png)
Firefox
![selection_075](https://cloud.githubusercontent.com/assets/16792762/13210678/88e9d7d4-d957-11e5-8a58-2c89d71ec93a.png)

Step 3
Chrome
![selection_076](https://cloud.githubusercontent.com/assets/16792762/13210725/01dfed36-d958-11e5-92dd-795e60e7e826.png)
Firefox
![selection_077](https://cloud.githubusercontent.com/assets/16792762/13210726/01e55f50-d958-11e5-987c-a4a8dcfd0657.png)

Step 4
Chrome
![selection_078](https://cloud.githubusercontent.com/assets/16792762/13210768/6a371e68-d958-11e5-8747-61652770c727.png)
Firefox
![selection_079](https://cloud.githubusercontent.com/assets/16792762/13210769/6a3c90aa-d958-11e5-9afc-521878714057.png)

Step 5
Chrome
![selection_080](https://cloud.githubusercontent.com/assets/16792762/13210966/497e98c0-d95a-11e5-944e-1e43566ce33a.png)
Firefox
![selection_081](https://cloud.githubusercontent.com/assets/16792762/13210967/497fcb64-d95a-11e5-8fc8-91763c451bbc.png)

Step 6
Chrome
![selection_082](https://cloud.githubusercontent.com/assets/16792762/13212293/0d32b598-d966-11e5-8b96-c8312893d2b6.png)
Firefox
![selection_083](https://cloud.githubusercontent.com/assets/16792762/13212294/0d39688e-d966-11e5-8766-05b4f86bff19.png)

**Comment by NishantUpadhyay-BTC** [comment]
@neerajkhatri-btc  For agreement page, I have fixed this issue. But I don't think that there is any need to fix for other pages. So we can put this on hold for now.

**Comment by NishantUpadhyay-BTC** [comment]
@HirenBhalani-BTC  Can you please tell me, in which branch these changes are available? Because I still be able to reproduce this.

**Comment by neerajkhatri-btc** [comment]
@NishantUpadhyay-BTC : this issue is fixed.
