### ISSUE TITLE
 Partial Block for PRs should turn cabin grey in Lodgings view 

### ISSUE THREAD

**Issue by NishantUpadhyay-BTC** [NishantUpadhyay-BTC/BLISS-Issue-Tracking#201]
Currently when we block out a cabin for two events using the "Partial Blocking" feature, the cabin shows up with a Grey background in the Lodgings view. However, if we only check the "PB" box, without assigning a second event, then the cabin shows up with that event color. We'd like for the cabin background to show up grey even if only one event is assigned to it and "PB" is checked.

**Comment by neerajkhatri-btc** [comment]
@NishantUpadhyay-BTC : this issue is fixed.
