### ISSUE TITLE
Reservations, Payments, New Payment: default payment type should by cc

### ISSUE THREAD

**Issue by NishantUpadhyay-BTC** [NishantUpadhyay-BTC/BLISS-Issue-Tracking#202]
When entering a new payment, the default payment type is currently Cash. Please change this to CC, but also please preserve the current list order.

**Comment by neerajkhatri-btc** [comment]
@NishantUpadhyay-BTC : 

Office UI
1. Reservation > Payment > New Payment
   - Show Purchase , Purchase  Button Two Times
2. When Select 'Cash' and again Select 'CC' 
   - Show 'Record' and 'Purchase'

**Comment by neerajkhatri-btc** [comment]
@NishantUpadhyay-BTC : this issue is fixed.
