### ISSUE TITLE
Reservation E-mail goes into spam

### ISSUE THREAD

**Issue by neerajkhatri-btc** [NishantUpadhyay-BTC/BLISS-Issue-Tracking#21]
![selection_096](https://cloud.githubusercontent.com/assets/16792762/13278453/9414e090-daf6-11e5-9d76-4311c5b0b9f0.png)

**Comment by NishantUpadhyay-BTC** [comment]
@neerajkhatri-btc  I think this is gmail account specific issue. When I send mail to my account it is going in my inbox but in your case it is going to spam box. May be this depends on some security level or something else. What we can do for now is update flash message and inform them to check their spam email. I have seen such flash message in many websites where they suggest to check spambox.
Let's put this on hold by just  updating flash message.
@AmitPatel-BoTreeConsulting  Please give your suggestions.

**Comment by amitpatelx** [comment]
@NishantUpadhyay-BTC check this http://blog.mailgun.com/tips-tricks-avoiding-gmail-spam-filtering-when-using-ruby-on-rails-action-mailer/ which can be useful reason why gmail mark it as spam.

Few more links 
https://www.igvita.com/2007/07/21/sendmail-spam-filter-tricks-in-rails/
http://stackoverflow.com/a/6395721/517483
http://shapeshed.com/getting-email-through-spam-filters-from-a-rails-app/
http://serverfault.com/questions/227242/prevent-mail-being-marked-as-spam

**Comment by NishantUpadhyay-BTC** [comment]
@neerajkhatri-btc Please check this issue now.

**Comment by neerajkhatri-btc** [comment]
@NishantUpadhyay-BTC  : This issue is fixed.

**Comment by neerajkhatri-btc** [comment]
@NishantUpadhyay-BTC : Please check this issue and fix it

**Comment by NishantUpadhyay-BTC** [comment]
@neerajkhatri-btc  We have changed the flow of reservation confirmation and we are following now the original reservation confirmation flow which means office user will check details and confirm reservation and then send email so this issue will no more exists. We can close it now.

**Comment by neerajkhatri-btc** [comment]
@NishantUpadhyay-BTC : this issue is fixed.
