### ISSUE TITLE
UI issue in I - Phone

### ISSUE THREAD

**Issue by neerajkhatri-btc** [NishantUpadhyay-BTC/BLISS-Issue-Tracking#212]
1. On Personal Retreat Availability > Gender > Willing to share

![img_0002](https://cloud.githubusercontent.com/assets/16792762/15143427/4d3353de-16c7-11e6-873e-49833165e59f.PNG)

**Comment by NishantUpadhyay-BTC** [comment]
@neerajkhatri-btc This issue is fixed and looks like too old than the current version. You can close it. I don't think that this is still exists in iphone. Please check.

**Comment by neerajkhatri-btc** [comment]
@NishantUpadhyay-BTC : pls fix that
1. When Touch Header Text 'Breitenbush Hot Springs - Retreat and Conference Center' and See![img_0002](https://cloud.githubusercontent.com/assets/16792762/15143427/4d3353de-16c7-11e6-873e-49833165e59f.PNG)

**Comment by neerajkhatri-btc** [comment]
@NishantUpadhyay-BTC : this issue is fixed.
