### ISSUE TITLE
Problems with Locking Lodging

### ISSUE THREAD

**Issue by NishantUpadhyay-BTC** [NishantUpadhyay-BTC/BLISS-Issue-Tracking#216]
- [ ]  If you lock a lodging, it lets others put someone in the cabin without any notification. See the original feature ticket for how this should actually function. 
- [ ] Look at "Daria Callie", 5/16. Note that trillium is locked, but if you click inside, you get the option to lock it again. This option should not be present for a lodging that is already locked.
- [ ]  If you try to lock a cabin and do not put a note in, it does not lock it and gives no warning. Please see the original feature ticket for how this should function.

**Comment by neerajkhatri-btc** [comment]
#261 : This issue similer to
