### ISSUE TITLE
Login form should not be displayed on header of forgot password screen. It gets displayed when click reset password button without adding  e-mail ID

### ISSUE THREAD

**Issue by neerajkhatri-btc** [NishantUpadhyay-BTC/BLISS-Issue-Tracking#22]
Step 1. enter data in Personal Retreat Availability page and click check availability button
Step 2. Select any lodging and reserve button click
![selection_065](https://cloud.githubusercontent.com/assets/16792762/13281921/7ab6c648-db0c-11e5-86e9-a9acb1525bb5.png)
Step 3. Click forgot password
![selection_097](https://cloud.githubusercontent.com/assets/16792762/13281984/bae664e4-db0c-11e5-9d7f-91309374e687.png)
Step 4. Click reset password
![selection_098](https://cloud.githubusercontent.com/assets/16792762/13281985/bae96766-db0c-11e5-9afd-d1d2643b8efa.png)

**Comment by NishantUpadhyay-BTC** [comment]
@neerajkhatri-btc  This is fixed. please test.

**Comment by neerajkhatri-btc** [comment]
@NishantUpadhyay-BTC : This is fixed.
