### ISSUE TITLE
#1338 -  Guest UI: Agreements: Text changes 

### ISSUE THREAD

**Issue by NishantUpadhyay-BTC** [NishantUpadhyay-BTC/BLISS-Issue-Tracking#223]
Alcohol and Drugs: missing space between “...Breitenbush.We...” - should be "...Breitenbush. We.."

Traction Devices: Change: "Date dependent (if res spans Nov 1st – April 1st). Chains or traction tires are required Nov 1st through April 1st."
To:
"Chains or traction tires are required Nov. 1st through Apr. 1st."

Please change: "Please leave your tea pots, hair dryers, hot plates and other high consumption devices at home."
to: "Please leave your tea pots, hair dryers, hot plates and other power-hungry devices at home."

**Comment by NishantUpadhyay-BTC** [comment]
For Traction Tires - we still need you to remove the first sentence: "Date dependent (if res spans Nov 1st – April 1st)"

Also - Is it possible to have the Traction Device warning actually be date dependent? I.e. - it only displays if the dates for the reservation cross over the time when we would give that warning (Nov 1 - April 1)?

Finally, please use the following text for "Driving Directions:

"GPS or Internet directions can get you dangerously lost! Please only use the directions provided in the email confirmation."

Note that the first sentence should be bold. We see that the current bold text is not quite bold enough - is there a way to make the bold more prominent?

**Comment by neerajkhatri-btc** [comment]
@NishantUpadhyay-BTC : this issue is fixed.
