### ISSUE TITLE
#1337 - Guest UI: Guest Details Page: Special Diet Help text change 

### ISSUE THREAD

**Issue by NishantUpadhyay-BTC** [NishantUpadhyay-BTC/BLISS-Issue-Tracking#224]
Please change: "...even if you are sensitive to a one of the three..."
to
"even if you are sensitive to one of the three..."

Also change “glutten”
to
"gluten"

**Comment by NishantUpadhyay-BTC** [comment]
One more change - here's the new text for special diet help:

“The special diet option has no gluten, egg or dairy ingredients, though our food is prepared in a kitchen where gluten-containing foods are cooked. If you sign up for this option, you are expected to always eat the special diet option, even if you are sensitive to one of the three. For example, if you choose the special diet option because you are sensitive to gluten, but you like eggs, you are still expected to eat the eggless alternative."

**Comment by neerajkhatri-btc** [comment]
@NishantUpadhyay-BTC : this issue is fixed.
