### ISSUE TITLE
#1334 -  Guest UI: User Profile: Gender Help Text 

### ISSUE THREAD

**Issue by NishantUpadhyay-BTC** [NishantUpadhyay-BTC/BLISS-Issue-Tracking#227]
The help text for Gender on the User Profile page should read:

"While Breitenbush’s policy is to honor each person’s declared gender, we currently are able to provide only two gender options for you to choose from.”

**Comment by NishantUpadhyay-BTC** [comment]
The gender help text is missing some words in the second sentence. I noticed this on the Availability page and on the Guest Details page. The second sentence should read:

"While Breitenbush’s policy is to honor each person’s declared gender, we currently are able to provide only two gender options for you to choose from.” just as it is in the description of this ticket.

**Comment by neerajkhatri-btc** [comment]
@NishantUpadhyay-BTC : this issue is fixed.
