### ISSUE TITLE
#1331 - Guest UI: Personal Retreat Availability Page: Change Descriptive Text

### ISSUE THREAD

**Issue by NishantUpadhyay-BTC** [NishantUpadhyay-BTC/BLISS-Issue-Tracking#228]
The sub-heading on this page has descriptive text that reads:

"Check Specific Dates or Browse Availability on the Calendar"

Please change this to read:

"Begin your reservation by providing the following information:"

**Comment by NishantUpadhyay-BTC** [comment]
The text has not changed at all I'm afraid. I'm talking about the text that's currently right under the progress bar on the "Personal Retreat Availability" page. We need to change this text to ""Begin your reservation by providing the following information:" . Also, please make the style and spacing match the descriptive text of other pages - remove the Bold and add some space between the text and the progress bar so that it matches other pages. Thanks!

**Comment by neerajkhatri-btc** [comment]
@NishantUpadhyay-BTC : this issue is fixed.
