### ISSUE TITLE
Flash message remove "No route matches "https://mandala.breitenbush.com:10443/availability/check_availability""

### ISSUE THREAD

**Issue by neerajkhatri-btc** [NishantUpadhyay-BTC/BLISS-Issue-Tracking#23]
Step 1. Enter Number Of Nights
Step 2. Enter Of Guests (including children)
Step 3. Enter minimum number of beds and click check availability
Step 4. Enter valid e-mail(neeraj.khatri@botreetechnologies.com) and password(OCGXSPUQ) and click sign in button. 
![selection_099](https://cloud.githubusercontent.com/assets/16792762/13282672/2b808e34-db10-11e5-96ca-679671fd5253.png)

**Comment by NishantUpadhyay-BTC** [comment]
@neerajkhatri-btc  this is fixed. Please test

**Comment by neerajkhatri-btc** [comment]
@AmitPatel-BoTreeConsulting : this is fixed.
