### ISSUE TITLE
#1319 -  Guest UI: Reserve Now: Gender Specific and Adult Only Warning - change text 

### ISSUE THREAD

**Issue by NishantUpadhyay-BTC** [NishantUpadhyay-BTC/BLISS-Issue-Tracking#230]
Trying to book a person of the opposite gender during a gender only time:
The Gender warning message displayed when user clicks "Reserve now" for one of the available lodgings reads:
"You are trying to book a reservation during a gender-specific time for a guest of the opposite gender. Please verify this guest is of the correct gender for this time period, or cancel this reservation." - However, user has been taken back to the Availability table - so there is no way to verify the gender or cancel the reservation from this screen. In fact, the reservation has not even been started yet.

So, let's change the text of this error to:

"You are trying to book a reservation during a gender-specific time for a guest of the opposite gender. Please choose different dates for your reservation."

Please also check the text for Adult Only warnings for this same error message and correct as above.

**Comment by neerajkhatri-btc** [comment]
@NishantUpadhyay-BTC : this issue is fixed.

**Comment by neerajkhatri-btc** [comment]
@NishantUpadhyay-BTC : this issue is fixed.
