### ISSUE TITLE
#1306 -  Guest UI: Prohibit reservations that have more beds than people 

### ISSUE THREAD

**Issue by NishantUpadhyay-BTC** [NishantUpadhyay-BTC/BLISS-Issue-Tracking#232]
During our tests, it was possible to make a reservation that contained more beds than people. This should be prohibited.

I can see a couple of ways to do this. Optimally, the drop-down menu for minimum # of beds and the drop-down menu for # of guests would be linked somehow, so that if you chose 3 guests you could not choose more than three beds - but conversely if you chose three beds you could not choose fewer than three guests. Both of these drop down menus would then have to change dynamically in real time - so the guest couldn't, for instance, choose two guests, then choose three beds.

Another, less attractive though perhaps easier option would be to present the user with an error when they try to select more beds than people - -either right after the selection, or if needed when they check for available lodgings.

Perhaps you have other ideas?

**Comment by NishantUpadhyay-BTC** [comment]
When user select three beds then the dropdown value for guests' count will automatically set to 3 and if then user tries to change it to less than 3 then show a message. Same for the opposite case, if user choose 3 guests then the bed value set to 3 and then user can select less bed count but if user try to select more bed counts then again show message warning and reset the values.

**Comment by neerajkhatri-btc** [comment]
@NishantUpadhyay-BTC : this issue is fixed.
