### ISSUE TITLE
#1307 -  Guest UI: No G.P. for PV, Tent Sites, Lodge Rooms 

### ISSUE THREAD

**Issue by NishantUpadhyay-BTC** [NishantUpadhyay-BTC/BLISS-Issue-Tracking#233]
For PV sites, Platform Tents, "Your Tent" sites and Lodge Rooms, Guaranteed Privacy is not an option, because in these lodgings 1=Full (so they are already guaranteed to be private by nature).

If a user chooses "Guaranteed Privacy" in initial search, these lodgings should still be displayed when available, but if the user reserves them G.P. rates should not be applied.

**Comment by NishantUpadhyay-BTC** [comment]
G.P. should not be an available option for a tent, tent site, PV site or Lodge Room. So, if user chooses GP in search, it's ok if these lodgings display as available, but once selected via Reserve All, then no G.P. rates should be applied, and no controls or information about GP should be displayed in Guest Details, Reservation Summary or Thank you Page.

**Comment by neerajkhatri-btc** [comment]
@NishantUpadhyay-BTC : this issue is fixed.
