### ISSUE TITLE
#1309 -  Guest UI: PR Availability: Change positionof "No Lodgings Found..." notification 

### ISSUE THREAD

**Issue by NishantUpadhyay-BTC** [NishantUpadhyay-BTC/BLISS-Issue-Tracking#235]
When no available lodgings are found, the "No Lodgings Found..." notice appears in a light-red bar across the top of the page. On many screens the user has scrolled down to click the "Check Availability" (a.k.a "Check for Available Lodgings") button - and so they do not see this message.

A couple of possibilities for correcting this: 1. Page auto-scrolls to top when the notice is presented or 2. (preferred) the notice appears right beside the "Check Availability/Check? for Available Lodgings" button.

**Comment by neerajkhatri-btc** [comment]
@NishantUpadhyay-BTC : this issue is fixed.
