### ISSUE TITLE
#1310 -  Guest UI: Availability Page: Availability Table scroll ability should be more obvious 

### ISSUE THREAD

**Issue by NishantUpadhyay-BTC** [NishantUpadhyay-BTC/BLISS-Issue-Tracking#236]
One hang up during out testing on Wednesday the 18th was that several people did not realize they could scroll the Availability Table. This caused confusion, e.g., "This page says it's showing availability for the next six months -but I can only see a few weeks out."

We need to find a way to make the scrolling ability more obvious- - perhaps using edge undershadowing like the example link Sherry sent a few months back.

**Comment by NishantUpadhyay-BTC** [comment]
​http://lea.verou.me/2012/04/background-attachment-local/

Note in this demo they only show horizontal shadows top and bottom - though we'd need one along the left and right edges as well.

**Comment by neerajkhatri-btc** [comment]
@NishantUpadhyay-BTC : this issue is fixed.

**Comment by NishantUpadhyay-BTC** [comment]
I checked with the BLISS team about this yesterday and our unanimous opinion is that both the shadowing and the scroll bars need to be a bit more obvious. So:
- Please make the undershadowing darker and a bit thicker.
- Please also make the scroll bar on the right side a bit darker and thicker.

**Comment by neerajkhatri-btc** [comment]
@NishantUpadhyay-BTC : this issue is fixed.
