### ISSUE TITLE
#1311 -  Guest UI: PR Availability: Tents not displaying when # of guests > 2 

### ISSUE THREAD

**Issue by NishantUpadhyay-BTC** [NishantUpadhyay-BTC/BLISS-Issue-Tracking#237]
Available Tent Sites and Platform tents should show up in the Available Lodgings list regardless of the number of guests chosen. Currently these do not display when # of guests is greater than 2.

To test this, find a period where platform tents and tent sites are available, then search for available lodgings on those dates with 2 guests. You'll see the available tent sites and platform tents show up in the available lodgings list. Now change number of guests to 3 or 4 and check for lodgings again. The tent sites and platform tents disappear.

**Comment by neerajkhatri-btc** [comment]
@NishantUpadhyay-BTC : this issue is fixed.
