### ISSUE TITLE
#1312 -  Guest UI: User sessions are not timing out. 

### ISSUE THREAD

**Issue by NishantUpadhyay-BTC** [NishantUpadhyay-BTC/BLISS-Issue-Tracking#238]
Today I opened up a laptop that we used in the "Happy Hour" tests two days ago. When the laptop "woke up" the web browser was still open to a guest user session. As an experiment, I clicked on the link to take me to the user's account page - and it worked just fine. This should not have happened. Instead, I should have been prompted to log back into my account. This is a serious security issue.

In the original spec for the Guest UI, we called for two different timers -one for an individual reservation, and one for the user session itself. We wanted to make sure that if a user walked away from a reservation that it would get cleared from the system AND we wanted to make sure that if a user walked away from their login session that someone couldn't walk up to that same computer and continue making a new or existing reservation masquerading as that user. As development progressed I think we forgot about these dual use-cases and dropped the session timer -only went with the reservation timer. We need to return to this feature and implement a user-session timeout to preserve login ID security.

IIMHO the session timer should be shorter than the reservation timer - perhaps as short as 5 minutes. So after 5 minutes of inactivity, any attempt to modify a the reservation, start a new reservation or navigate to the account page would force the user to log in again -but would then take the user back to their existing reservation (if the reservation timer had not also run out). If the reservation timer had also run out, then they'd be logged back in and taken to the Availability page.

Questions? Thoughts?

**Comment by neerajkhatri-btc** [comment]
@NishantUpadhyay-BTC : this issue is fixed.

**Comment by neerajkhatri-btc** [comment]
@NishantUpadhyay-BTC : this issue still not working in fire fox. so pls fix that

**Comment by NishantUpadhyay-BTC** [comment]
I just happened to test this while I was testing other features. It's working pretty well, except when I allowed my session to time out (i.e., longer than 10 minutes) and clicked on the "I'm still here!" button, I was taken back to the Availability screen with no explanation. If user has missed their opportunity and timeout has been reached then either one of two things should happen:

The user clicks on "I'm still here!" and is taken to the Login Page with a message at the top that says: "Sorry, but your login session has timed out due to inactivity."

If the session timer expires while the notice is still up, the notice disappears and the user is taken to the Login screen with the same message above. 

Once the user logs back in, if the reservation timer has not yet expired, then they are returned to the Reservation Details page for that reservation. If the reservation timer has also expired, then they are taken to the Availability page with a message "Sorry, but you have exceeded the allotted time for completing your previous reservation (30 min.) and will have to start a new one."

**Comment by NishantUpadhyay-BTC** [comment]
This is closed by client so I am closing it.
