### ISSUE TITLE
#1313-  Guest UI: Mobile View: Availability Table: scrolling issues 

### ISSUE THREAD

**Issue by NishantUpadhyay-BTC** [NishantUpadhyay-BTC/BLISS-Issue-Tracking#239]
On both Android and iPhone, the Availability Table is not scrolling properly.
- Column Headers should be static
- Row headings should be static
- We need undershadowing to make scroll ability more obvious. 

Please test on both Android and iPhone, newer and older browsers.

**Comment by neerajkhatri-btc** [comment]
@NishantUpadhyay-BTC : this issue is fixed.
