### ISSUE TITLE
Availability table should display first 14 days and then it should be scroll-able. 

### ISSUE THREAD

**Issue by neerajkhatri-btc** [NishantUpadhyay-BTC/BLISS-Issue-Tracking#24]
![selection_100](https://cloud.githubusercontent.com/assets/16792762/13284107/22f62528-db18-11e5-9cbb-0f832e3f0c5e.png)

**Comment by NishantUpadhyay-BTC** [comment]
@neerajkhatri-btc This is fixed. Please test.

**Comment by neerajkhatri-btc** [comment]
@NishantUpadhyay-BTC : This is fixed.
