### ISSUE TITLE
#1314 - Guest UI: Mobile View: PR Availability: Date Selection issues

### ISSUE THREAD

**Issue by NishantUpadhyay-BTC** [NishantUpadhyay-BTC/BLISS-Issue-Tracking#240]
On both Android and iPhone, month navigation arrow buttons are not functioning to change from one month to another.

Also we noticed that the months are getting partially hidden under other parts of the page - possibly the footer? - and don't appear completely without some non-intuitive scroll work. We may want to re-work date selection for mobile devices to make this more appropriate specific for that interface. Thoughts? Ideas?

**Comment by neerajkhatri-btc** [comment]
@NishantUpadhyay-BTC : this issue close by client.so close it.
