### ISSUE TITLE
#1315 - Office UI: Guest Search not working in Safari or Chormium

### ISSUE THREAD

**Issue by NishantUpadhyay-BTC** [NishantUpadhyay-BTC/BLISS-Issue-Tracking#241]
Guest search is not working in Chromium Version 46.0.2490.86 (64-bit) or in Safari Version 9.1 (11601.5.17.1), but is working in Firefox 35.0.1. All of these are using a Macbook Pro, OS X 10.11.4.

In Chromium and Safari, I see the additional option to search for "Organization Name" which is weird. Where did that come from? Don't see this in Firefox.

When I enter search names in Chromium or Safari and hit return or tab nothing happens.

**Comment by neerajkhatri-btc** [comment]
@NishantUpadhyay-BTC : this issue is fixed.
