### ISSUE TITLE
#1317 Guest UI: Availability Page: Need to show Gender Specific and Adult Only times 

### ISSUE THREAD

**Issue by NishantUpadhyay-BTC** [NishantUpadhyay-BTC/BLISS-Issue-Tracking#243]
We need a way to show special times in the Availability Table. So, for example, a male guest might see lodgings available for a certain date, and not knowing that the dates are a "Women Only " camp might start a search for lodgings, only to find out that it's a Women Only time. It would be kinder to show this up front.

One possibility: Display a large, uppercase bold "M" (for Men only) "W" (Women only) or "A" (Adults only) to the right of dates for which these apply. We'd also need to include an explanation of these letters in the key above (where the colors are now delineated).

We'd like to see how this looks, and will likely discuss this further.

**Comment by neerajkhatri-btc** [comment]
@NishantUpadhyay-BTC : this issue is fixed.
