### ISSUE TITLE
#1318 -  Guest UI: PR Availability: GP getting cached inappropriately 

### ISSUE THREAD

**Issue by NishantUpadhyay-BTC** [NishantUpadhyay-BTC/BLISS-Issue-Tracking#244]
If #guests >1 then GP should no longer be applicable. However, currently when user chooses GP, then changes #guests to any number > 1, GP is still being applied to the reservation. This should not be.

Also, when making several consecutive reservations, if user selects GP for any of them, then that choice is being carried over to all subsequent reservations. This should not be.

It looks like perhaps all user choices on the Personal Retreat Availability Page are being cached by the Browser - including arrival date, number of nights, etc. It might be preferable to not cache any of this information -but G.P. absolutely shouldn't be cached in this way, as it effects the cost of the reservation.

**Comment by neerajkhatri-btc** [comment]
#261
