### ISSUE TITLE
#1321 -  Guest UI: Guest Allocation issue #1 

### ISSUE THREAD

**Issue by NishantUpadhyay-BTC** [NishantUpadhyay-BTC/BLISS-Issue-Tracking#246]
Please see Res ID 81505 (temporary) on Staging. Go to the Reservation Details page. Notice how the guest "Jacob" was left "Unassigned". The app should have assigned Jacob to C5 with the rest of the guests.

Now, it's likely that Office Staff will catch this sort of thing, since we're checking each reservation - and they'd see it on the confirmation page when they see the error: "Confirm anyway even though it's overbooked". However, we'd prefer the app to take care of this without intervention, since we're hoping that Office Staff checking will soon not be needed.

**Comment by neerajkhatri-btc** [comment]
@NishantUpadhyay-BTC : this issue is fixed.

**Comment by NishantUpadhyay-BTC** [comment]
Please see resID 83361. It's for 4 people in a non-bath cabin. Notice that 2 of them are "Unassigned", which means that the user was charged for only 2 people. All four party members should have been assigned to that lodging. Also see reservation 83365. Same issue, but for a Lodge Room.

**Comment by neerajkhatri-btc** [comment]
@NishantUpadhyay-BTC : this issue has been fixed.
