### ISSUE TITLE
#1325 -  Guest UI: Guest Allocation issue #2 

### ISSUE THREAD

**Issue by NishantUpadhyay-BTC** [NishantUpadhyay-BTC/BLISS-Issue-Tracking#249]
Please see reservation ID 81479 on staging.
Note that an A-Row cabin was chosen, even though B-Row cabins were available. I believe per the Workflow Doc we asked that B-Row cabins be given preference. Please consult that document for this and other lodging allocation order preferences.

**Comment by NishantUpadhyay-BTC** [comment]
Give priority for reservation in below order for each lodging type:

For tent sites,
'6', '8' , '10', '12', '14', '16', '7', '9', '11', '13', '15', '17', '5'

for Tents
"Rabbit", "Deer", "Wolf", "Bear", "Hawk", "Elk", "Beaver", "Cougar", "Raven"

For personal vehicle sites
'PV1', 'PV18','PV4', 'PV2', 'PV3'

For plumbing cabin
B3 to B9 then A1 to A8 and finally B1 and B2

For non-plumbing cabin
C1 to C8, then D1 to D6 (d7 and d8 are dorms which will not be available for guest UI reservation) then E1 to E4 then F1 to F6 and at last G1

For Lodges Orchid and Trillium

**Comment by neerajkhatri-btc** [comment]
@NishantUpadhyay-BTC : this issue is fixed.
