### ISSUE TITLE
Date format in availability table

### ISSUE THREAD

**Issue by NishantUpadhyay-BTC** [NishantUpadhyay-BTC/BLISS-Issue-Tracking#25]
Availability Table:
-Date format in the availability table should be MM-DD-YYYY

![selection_803](https://cloud.githubusercontent.com/assets/6542029/13310369/8fdb3456-dbab-11e5-8414-12a843f93c90.png)

**Comment by HirenBhalani** [comment]
branch:  hb_issue_25.develop

**Comment by NishantUpadhyay-BTC** [comment]
This is merged in develop branch

**Comment by neerajkhatri-btc** [comment]
@NishantUpadhyay-BTC : this is fixed
