### ISSUE TITLE
#1327 -  Guest UI: Reservation Details: Ability to remove G.P 

### ISSUE THREAD

**Issue by NishantUpadhyay-BTC** [NishantUpadhyay-BTC/BLISS-Issue-Tracking#251]
On the Reservation Details screen, if user has chosen "Guaranteed Privacy" in previous screen please provide the ability to change back to "Willing to Share". This could be accomplished via the exact same radio buttons as provided on the Personal Retreat Availability page.

Note that we can't have this operate the other direction -i.e. - if the user has already chosen "Willing to Share", they can't now chose "Guaranteed Privacy" on the Details page, since that might invalidate the chosen lodging. Opening up a GP reservation does not have that consequence.

**Comment by neerajkhatri-btc** [comment]
@NishantUpadhyay-BTC : this issue is fixed.
