### ISSUE TITLE
#1329 -  Guest UI: Payment Screen: Feedback on Error 

### ISSUE THREAD

**Issue by NishantUpadhyay-BTC** [NishantUpadhyay-BTC/BLISS-Issue-Tracking#253]
When user input on payment screen fails, we need some feedback. For instance, currently a mis-entered card number produces no change. Perhaps in that instance the box around the number field changes red and an accompanying error message appears, such as "Please correct the fields outlined in red" - a generic error message like that could be used for any number of errors or omissions.

**Comment by neerajkhatri-btc** [comment]
@NishantUpadhyay-BTC : this issue is fixed.
