### ISSUE TITLE
#1332 -  Guest UI: General Design: Non-selected radio buttons and dividing lines darker 

### ISSUE THREAD

**Issue by NishantUpadhyay-BTC** [NishantUpadhyay-BTC/BLISS-Issue-Tracking#254]
The color choice for the borders of non-selected radio buttons (e.g. Special Diet box) as well as the borders of table cells (e.g. on the Guest Details page) are just a bit too light/transparent. Could we please darken these just a bit site-wide?

**Comment by neerajkhatri-btc** [comment]
@NishantUpadhyay-BTC : this issue is fixed.
