### ISSUE TITLE
#1333 - Guest UI: Guest Details Page: Additional Comments: Add character count and change error text.

### ISSUE THREAD

**Issue by NishantUpadhyay-BTC** [NishantUpadhyay-BTC/BLISS-Issue-Tracking#255]
Please add a small standard character count above the upper-right corner of the "Any Additional Comments" box. Format = ###/Max (e.g., if 255 is the max number of characters, and the user has typed 50 characters, this would read: 50/255).

Also please change the the character limit error text to read:

"Your comment exceeds the character limit. Please contact our Reservations Office if you have additional information you wish to pass along".

**Comment by NishantUpadhyay-BTC** [comment]
Please add a long text in comment box, it should be more than 255 characters and then click continue. 

![selection_020](https://cloud.githubusercontent.com/assets/6542029/15564240/ac451692-232d-11e6-86b4-648a3b237489.png)

**Comment by neerajkhatri-btc** [comment]
@NishantUpadhyay-BTC : this issue is fixed.
