### ISSUE TITLE
#1341 - Guest UI: Guest Details: Additional Guest Gender should default to null

### ISSUE THREAD

**Issue by NishantUpadhyay-BTC** [NishantUpadhyay-BTC/BLISS-Issue-Tracking#256]
Currently additional guests' gender defaults to Male. Please change this
 to null/none. I believe these are already required fields, but if not
 please make them so. In this way users are forced to consciously mark
 gender for all guests.

**Comment by neerajkhatri-btc** [comment]
@NishantUpadhyay-BTC : this issue is fixed.
