### ISSUE TITLE
#1342: Guest UI: Cancellation Policy (Deposit Only) remove last sentance

### ISSUE THREAD

**Issue by NishantUpadhyay-BTC** [NishantUpadhyay-BTC/BLISS-Issue-Tracking#257]
In the "Deposit Only" cancellation policy, please remove the last sentence: "We accept Cash, Check (including travelers checks), Visa, MC  and Discover." (true, but doesn't apply to this interface, since it will  only take cc and paypal. Also this sentence does not appear in the "Full Amount" cancellation policy, so I think we're safe to just delete it).

**Comment by neerajkhatri-btc** [comment]
@NishantUpadhyay-BTC : this issue is fixed.
