### ISSUE TITLE
#1343 - Guest UI - "We're Sorry but Something Went Wrong" - also on office ui...

### ISSUE THREAD

**Issue by NishantUpadhyay-BTC** [NishantUpadhyay-BTC/BLISS-Issue-Tracking#259]
I was trying to test various availability scenarios on staging today and got a strange error in both the Office UI and Guest UI. Also noticed that the Availability page did not seem to be displaying correct available lodgings.

First, I brought up our "Check Availability" guest in the Office UI, and tried to start a new reservation starting tomorrow (Wed, May 25, 2016) for cabin B7- which is available to share. Upon selecting that cabin - either via that green dot at the bottom or by opening up the cabin view and choosing 'Reserve Now", I was presented with the error: "Something went wrong. Please try again When you click OK, we will refresh the screen to give you an updated view. (This may take a moment)". I could not reserve the cabin. However, I was able to place the guest into the Dorm- D7. I removed the guest from D7 and deleted that test reservation.

Now I go to the Availability screen. I expect to see one plumbing cabin available - since B7 is available to share - but the Availability screen shows no plumbing and no non-plumbing cabins available. Then proceed to the PR availability page and I do a search for available lodgings on 5/25 for a single female willing to share- and am presented with a Non-Plumbing cabin! This could only be the Dorm space - which should not appear here. But why wasn't it showing B7- a plumbing cabin that was available to share?

Then, I select the non-plumbing cabin by clicking "Reserve Now" and login using the ID for guiguest024.breitenbush.com. Immediately after completing login I am presented with the error:
"We're sorry, but something went wrong. If you are the application owner check the logs for more information."

NOTE: All of this was around 5PM-5:20 PDT.

So, I then manually navigated back to ​https://guestuitest.breitnet.net (by typing manually, since there was no option for returning on the error page, and no way to use the back button). I found that I was logged in as Gui Guest024, and checked availability for the same date. I got the same result and once again chose to reserve the non-plumbing cabin. This time I was presented with the option to choose my existing reservation or cancel that one and start a new one (which is a very nice feature BTW -good thinking) - however, clicking either of these buttons returns me to the error message above.

So - it looks like there is some fundamental glitch that's preventing these reservations 24 hours out? This is a big deal, as we need to be able to make these- and it's a big deal that the Availability table was displaying incorrect data.

**Comment by neerajkhatri-btc** [comment]
@NishantUpadhyay-BTC : this issue is fixed.

**Comment by NishantUpadhyay-BTC** [comment]
When user searches for available lodgings:

If user searches for a single person, and the only available lodging for a particular type is shared lodging for the opposite gender, show that lodging in the available lodgings list, but in place of the "Reserve Now" button, display the message: "For this type of lodging, this system was only able to find shared lodgings for the opposite gender” 

If user searches for a multiple person reservation and the only lodging available for a particular type is shared, show that lodging in the available lodgings list, but in place of the 'Reserve Now" button, display the message- "For this type of lodging, this system was only able to find shared lodgings for a single person. "

**Comment by neerajkhatri-btc** [comment]
@NishantUpadhyay-BTC : this issue is fixed.

**Comment by NishantUpadhyay-BTC** [comment]
We need to add one more case;

If user searches for a single person, and gender is not known and the only available lodging for a particular type is shared, show that lodging in the available lodgings list, but in place of the "Reserve Now" button, display the message: "For this type of lodging, this system was only able to find shared lodging. To see if this lodging is available, please specify your gender above and search again.”

**Comment by NishantUpadhyay-BTC** [comment]
Here's what I've gotten from Office Staff:
- [x] if user searches for a single person, and gender is not known and the only available lodging for a particular type is shared, show that lodging in the available lodgings list, but in place of the "Reserve Now" button, display the message: "For this type of lodging, this system was only able to find shared lodging. To see if this lodging is available, please specify your gender above and search again.”
- [x] We need to implement friction in the Office UI that prevents a reservation from being confirmed if any party gender is unknown. I'm thinking the only place this needs to happen is at "Send and Confirm" and "Just Confirm". Do you need a separate ticket for this? 
- [x] If, for some reason, some reservation manages to get by us and a shared res without gender comes up in the Guest UI search (perhaps a reservation created before #1 above was implemented), then that lodging would appear in the Available Lodgings table with the following message in place of the "Reserve Now" button: 
  “A shared reservation for this lodging type might be possible, but will require talking to us in person, please call us at 503.843.3320 if you would like to book a shared reservation for this lodging."

**Comment by neerajkhatri-btc** [comment]
@NishantUpadhyay-BTC : this issue has been fixed.
