### ISSUE TITLE
Change date format of arrival and departure date

### ISSUE THREAD

**Issue by NishantUpadhyay-BTC** [NishantUpadhyay-BTC/BLISS-Issue-Tracking#26]
Check Availability page:

-Once the user chooses a date from the calendar popup for arrival date, the date should display in the format: Thursday, March 13, 2016 (i.e. - include day of week). Please also use this format for the departure date.

![selection_804](https://cloud.githubusercontent.com/assets/6542029/13310465/3d1ba178-dbac-11e5-82a7-3f8d1d7f1448.png)

**Comment by HirenBhalani** [comment]
branch : hb_issue_26.develop

**Comment by NishantUpadhyay-BTC** [comment]
This is merged in develop branch

**Comment by neerajkhatri-btc** [comment]
@NishantUpadhyay-BTC : This is fixed.
