### ISSUE TITLE
#1358 - Office UI: Special Times: Warnings and Stops

### ISSUE THREAD

**Issue by NishantUpadhyay-BTC** [NishantUpadhyay-BTC/BLISS-Issue-Tracking#261]
For special times (Adult-Only, Gender-Specific, Special) there are points in the checking and reserving workflow where we should get a "Notification" ( i.e. a red band at the top of the screen or a popup with a message informing us of the special time condition), and points in the workflow when we should get a "Stop", (i.e. a pop-up message or other inline notification that prevents the reservation from continuing until the violation is corrected). At other points, we might want to be able to continue with no further notification or stop. Right now, these Notifications and Stops are inconsistent. 

 I've attached a spreadsheet that explains how this should work using a matrix. 

[Special Times Warning Matrix.xlsx](https://github.com/NishantUpadhyay-BTC/BLISS-Issue-Tracking/files/285775/Special.Times.Warning.Matrix.xlsx)

**Comment by NishantUpadhyay-BTC** [comment]
when the period is Adult's only and user try to change date then stop user if age rule is violating because we don't know the age of user until the reservation gets created and after that we are asking of age details if the period is adult only. So I don't think that change date will require user to stop for age violation. Your thoughts?

Reply:

If user tries to change dates of an existing reservation where age for any guests in party is not known, and new dates touch an adult only time period, they should be prevented from doing this until the user specifies the age of all guests via the guest details tab.

For Reservations/availability tab, do you want to display message on top even reservation is created or not and user change the date and that date contains specific period?

Reply:
Yes.

**Comment by neerajkhatri-btc** [comment]
@NishantUpadhyay-BTC : pls see
1. Availability - Three Cases > Notification on date change from Calendar.
2. Adults Only - Change Date should stop user from reserving Lodging
3. Confirmation - Show Special time message on top of Confirmation.

**Comment by NishantUpadhyay-BTC** [comment]
@neerajkhatri-btc  client has closed this issue as it is fixed. So I am closing it.
