### ISSUE TITLE
#1357 - Guest UI: Special Times: No overlapping men/women only times 

### ISSUE THREAD

**Issue by NishantUpadhyay-BTC** [NishantUpadhyay-BTC/BLISS-Issue-Tracking#262]
Currently it's possible to create overlapping Men-Only and Women-Only times that overlap, effectively creating a time period where nobody can come. Can we prohibit this?

**Comment by NishantUpadhyay-BTC** [comment]
@neerajkhatri-btc Please reproduce this on staging.

**Comment by neerajkhatri-btc** [comment]
@NishantUpadhyay-BTC : this issue is fixed.
