### ISSUE TITLE
#1356 - Office UI: Special Times: Toggleable radio buttons 

### ISSUE THREAD

**Issue by NishantUpadhyay-BTC** [NishantUpadhyay-BTC/BLISS-Issue-Tracking#263]
Currently the radio buttons for Male Female and Adult are static state - once chosen they cannot be de-selected. Can we make it possible to toggle these on/off? We do have the ability to use the reset button, but this also wipes out dates.

**Comment by neerajkhatri-btc** [comment]
@NishantUpadhyay-BTC : this issue is fixed.

**Comment by neerajkhatri-btc** [comment]
@NishantUpadhyay-BTC : 
1. This is browser related issue. 
2. It was working fine in fire fox but not working in Chrome/Chromium

**Comment by neerajkhatri-btc** [comment]
@NishantUpadhyay-BTC : this issue is fixed.
