### ISSUE TITLE
#1355 - Office UI: Lock Lodging - auto view refresh on lock 

### ISSUE THREAD

**Issue by NishantUpadhyay-BTC** [NishantUpadhyay-BTC/BLISS-Issue-Tracking#264]
When we lock a lodging, the lock icon does not show up until we refresh the page or go to another date within the lock. Can you add a script to Auto-refresh the view upon lock so that the lock icon shows up immediately?

**Comment by NishantUpadhyay-BTC** [comment]
@neerajkhatri-btc   Please reproduce this on staging.

**Comment by neerajkhatri-btc** [comment]
@NishantUpadhyay-BTC: this issue is fixed.
