### ISSUE TITLE
#1353 -  Office UI: Add new guest type: "Staff Guest" 

### ISSUE THREAD

**Issue by NishantUpadhyay-BTC** [NishantUpadhyay-BTC/BLISS-Issue-Tracking#266]
Please add a new guest type "Staff Guest". This type should behave the same way as "Staff" when trying to book and event reservation with no lodging.

**Comment by neerajkhatri-btc** [comment]
@NishantUpadhyay-BTC : this issue is fixed.

**Comment by NishantUpadhyay-BTC** [comment]
This isn't working properly. I ought to be able to book an event reservation with no lodging when guest type = staff guest, exactly as I can when guest type = staff. With staff type, confirmation page presents a warning with a checkbox to book without lodging. This is not happening when guest type = staff guest.

**Comment by neerajkhatri-btc** [comment]
@NishantUpadhyay-BTC : this issue is fixed.

**Comment by NishantUpadhyay-BTC** [comment]
This has broken again. The user type "Staff Guest" is not allowing a reservation without lodging.

**Comment by neerajkhatri-btc** [comment]
@NishantUpadhyay-BTC : this issue has been fixed.
