### ISSUE TITLE
 #1352 - Office UI: Locking Lodgings: Lock info cacheing issue? 

### ISSUE THREAD

**Issue by NishantUpadhyay-BTC** [NishantUpadhyay-BTC/BLISS-Issue-Tracking#267]
On Staging, go to Reservations/Availability?, Go to June 12, pick Cabin B2 and choose "Lock Lodging" You will note that the lock dialogue already has dates chosen and a note in it. This error is random - does not happen all the time.

Possible data cacheing issue?

**Comment by NishantUpadhyay-BTC** [comment]
@neerajkhatri-btc As the client agree with this approach, we  can close his issue.

**Comment by neerajkhatri-btc** [comment]
@NishantUpadhyay-BTC : this issue is fixed.
