### ISSUE TITLE
 #1351 - Office UI: Locking Lodgings: Lock icon inconsistent in Availability view 

### ISSUE THREAD

**Issue by NishantUpadhyay-BTC** [NishantUpadhyay-BTC/BLISS-Issue-Tracking#268]
On staging, go to Reservations/Availability? view. Navigate to June 13th. Click on cabin B6 and lock the lodging with dates: June 12, 2015 through June 16, 2016.

Now navigate to June 12, and one by one select the dates of the lock period (12th, then 13th, then 14th). Notice how the lock icon disappears on 13th and the 16th. Why? Please correct this so that the locking icon displays consistently in Availability view on all days of the lock.

**Comment by NishantUpadhyay-BTC** [comment]
@neerajkhatri-btc  Can you please confirm that, this issues is reproducible on staging?

**Comment by neerajkhatri-btc** [comment]
@NishantUpadhyay-BTC : this issue is fixed.
