### ISSUE TITLE
#1349 - Guest UI: Thank you page: Thank you text 

### ISSUE THREAD

**Issue by NishantUpadhyay-BTC** [NishantUpadhyay-BTC/BLISS-Issue-Tracking#269]
Please change the Thank you text at the bottom of this page from:
"Thank you for your reservation. Once we review your reservation for accuracy, we'll send a confirmation email to <guest email>. Please contact our reservations office if you do not hear from us within 24 hours."

To:

"Thank you for your reservation. Once we review your reservation for accuracy, we'll send a confirmation email to <guest email> If you cannot find your confirmation email, please check your spam filter. Please contact our reservations office if you do not hear from us within 48 hours."

**Comment by neerajkhatri-btc** [comment]
@NishantUpadhyay-BTC : this issue is fixed.
