### ISSUE TITLE
Availability form changes

### ISSUE THREAD

**Issue by NishantUpadhyay-BTC** [NishantUpadhyay-BTC/BLISS-Issue-Tracking#27]
- [x] Willing to Share should default to Yes
- [x] Minimum # of beds not needed if # of guests = 1
- [x] Minimum # of beds should be required if # of guests is greater than or equal to 2

**Comment by NishantUpadhyay-BTC** [comment]
This changes are available in branch **25_2_issue_27.develop**

**Comment by NishantUpadhyay-BTC** [comment]
This is merged in develop branch

**Comment by neerajkhatri-btc** [comment]
@NishantUpadhyay-BTC : this issue fixed.
