### ISSUE TITLE
#1348 -  Guest UI: Navigation on "Reserve Now" when gender does not match special time 

### ISSUE THREAD

**Issue by NishantUpadhyay-BTC** [NishantUpadhyay-BTC/BLISS-Issue-Tracking#270]
If user has chosen dates that overlap a special time, but criteria does not match (e.g. wrong gender) and they click "Reserve Now" on an available lodging, currently they are presented with the warning popup and taken to the Availability Table. Instead, please leave them on the Available Lodgings/PR Availability page.

**Comment by neerajkhatri-btc** [comment]
@NishantUpadhyay-BTC : this issue is fixed.
