### ISSUE TITLE
#1345 -  Guest UI: PV Site Warning 

### ISSUE THREAD

**Issue by NishantUpadhyay-BTC** [NishantUpadhyay-BTC/BLISS-Issue-Tracking#272]
When user clicks "Reserve Now" for a PV site, present a warning popup:

"Total Length of your vehicle plus trailer must be 21’ or less to fit our PV sites."

Two buttons: "Yes: Continue" (continues reservation process) and "No: Cancel" (returns to Available Lodgings table)

**Comment by neerajkhatri-btc** [comment]
@NishantUpadhyay-BTC : this issue is fixed.
