### ISSUE TITLE
#1344 - Guest UI: Reservation Summary/Thank You: Add Total Number of Nights

### ISSUE THREAD

**Issue by NishantUpadhyay-BTC** [NishantUpadhyay-BTC/BLISS-Issue-Tracking#274]
On the Reservation Summary and Thank You pages, please add the Total Number of Nights:

e.g.:

Arrival
3PM on Mon, 6-27-16

Departure
3PM on Thu, 6-30-16

Number of nights:
3

**Comment by neerajkhatri-btc** [comment]
@NishantUpadhyay-BTC : this issue is fixed.
