### ISSUE TITLE
Remove Flash Message 'undefined method `id' for nil:NilClass'

### ISSUE THREAD

**Issue by neerajkhatri-btc** [NishantUpadhyay-BTC/BLISS-Issue-Tracking#275]
1. Date's should be like 
   ![selection_433](https://cloud.githubusercontent.com/assets/16792762/15650598/4ea59e2c-2697-11e6-9583-42cf9098d448.png)
2. Click Reserve now
   ![selection_434](https://cloud.githubusercontent.com/assets/16792762/15650618/825d71a4-2697-11e6-8fec-63e44c560e24.png)

**Comment by NishantUpadhyay-BTC** [comment]
@neerajkhatri-btc  We have to reproduce this issue with some different date combinations and lodgings and reservations to understand it.

**Comment by NishantUpadhyay-BTC** [comment]
@neerajkhatri-btc  I am unable to reproduce this issue. Please verify again.

**Comment by neerajkhatri-btc** [comment]
@NishantUpadhyay-BTC : i also unable to reproduce this issue so close it.

**Comment by neerajkhatri-btc** [comment]
#292
