### ISSUE TITLE
#1359 - Guest UI: Need a way to navigate back to current reservation.

### ISSUE THREAD

**Issue by NishantUpadhyay-BTC** [NishantUpadhyay-BTC/BLISS-Issue-Tracking#276]
After the user begins a new reservation, as long as they do not log out and the session timer has not run out, we need a way for them to return to the current reservation in progress from any page that does not already provide this explicitly. For example: Availability, PR Availability, Account Info. Could be a simple navigation buttons like the ones we've already provided at the top of the screen. Ideas?

**Comment by NishantUpadhyay-BTC** [comment]
As per my understanding, you want user to be able to visit last visited page of the reservation process which may be summary page, agreement page, guest party details page or payment confirmation page. And we don't need to redirect user to "thank you" page because at that time payment will already be done.

Paul's Reply:
 That's one way to handle it, yes. Or, we could always just return to the Guest Party Details page if they haven't paid yet. Then if they've already checked the Agreements they'd simply skip that step. Does that make sense? So the user navigates away from the current reservation - maybe they go double-check their airline flights, or they go back to the Breitenbush Home page to check on other events that are happening, or whatever. When they return to the reservation UI, then:

If their login session has not expired (i.e. return within 10 minutes), then they'd be returned to the Guest Party Details with no further friction. If they've already checked Agreements, then on "Continue" they'd skip to the Reservation Summary page and then on to payments, etc. 

OR

If their login session has expired but their reservation timer has not, then perhaps they'd go to the Availability Screen, and once logged in be presented with the existing message with the options "Go to Existing Reservation in Progress" or "Cancel and Start a New Reservation" - I don't remember the exact wording. Then on successful login, returned to Guest Party Details page. 

OR

If BOTH the Login Session timer AND the Reservation timer have expired, then proceed as in step 2, but on successful login perhaps they get a message that lets them know their prior reservation has expired and they need to start over (e.g. "You previously had a reservation in progress, but the time for completing that reservation has expired. Please start a new reservation."), then returned to the Availability Screen.

**Comment by NishantUpadhyay-BTC** [comment]
Change the order of tabs on header
Current Reservation - Return to Availability - Home

**Comment by neerajkhatri-btc** [comment]
@NishantUpadhyay-BTC : this issue is fixed.
