### ISSUE TITLE
#1350 -  Guest UI: Progress Bar 

### ISSUE THREAD

**Issue by NishantUpadhyay-BTC** [NishantUpadhyay-BTC/BLISS-Issue-Tracking#277]
We'd like to add a progress bar to the top of the Guest UI pages. This will provide feedback to the user about where they are in the reservation process, e.g. "Basic Information - Login - Reservation Details- Agreements - Summary - Payment"

![progress bar v 1](https://cloud.githubusercontent.com/assets/6542029/15769947/88936b08-297d-11e6-82bf-28c00f33721f.jpg)

I've attached a mockup of the "Progress Bar' from Sherry.

This appears under the title of each page of the reservation. The "Active" page is displayed in our standard deep green (e.g. "Reservation Details" in Sherry's example). Past steps are dark gray (e.g. "Basic Information" and "Login"), and future steps are light gray. Note also that we've changed the location and presentation of the session timer.

I think the "Login" box would be active through both the login page and the account info page.

**Comment by NishantUpadhyay-BTC** [comment]
This is looking pretty good. I have the following suggestions:

I Don't see any progress bar on the "Personal Retreat Availability" page. The step here should be "Basic Information".

When I get to the "Login" page, the progress bar appears, but "Login" is the first box. At this point, "Login" should be the second box, with "Basic Information" grayed and to the left.

Once I got to the "Reservation Details" I finally saw the entire progress bar, pretty much as it should be. 

Overall I think both the progress bar and the reservation timer below could be smaller both horizontally and vertically. They should provide a navigational aid, but right now are too visually dominating. I think they could be about 1/2 their current size and still do the job.

Sherry sent in her ideas for mobile, which I'll post in a separate comment.

**Comment by NishantUpadhyay-BTC** [comment]
"The progress bar on mobile I'm thinking we probably shouldn't shrink it that much to make it readable, but we don't want it taking up a huge amount of the screen up there either. Maybe something like below where the other bars are kind of collapsed and it only shows the current step (and the collapsed chunks give an indication of how many steps are left)?"

![progressbar-mobile](https://cloud.githubusercontent.com/assets/6542029/15997511/9754e09a-3152-11e6-83e6-0291bd97505a.jpg)

**Comment by neerajkhatri-btc** [comment]
@NishantUpadhyay-BTC : this issue is fixed.

**Comment by NishantUpadhyay-BTC** [comment]
OK -this is still looking weird to me. Let's try moving it up above the page titles (i.e. above the words "Personal Retreat Availability", "Breitenbush Account", etc.

**Comment by NishantUpadhyay-BTC** [comment]
Client has closed this issue. So I am going to close this.
