### ISSUE TITLE
Guest UI : Availability Table : Display wrong Details for 'LODGE ROOM'

### ISSUE THREAD

**Issue by neerajkhatri-btc** [NishantUpadhyay-BTC/BLISS-Issue-Tracking#278]
1. In Availability Table show 'LODGE ROOM' available this Date but actual see in this date 'Sun, 6-8-16' it will no available in available lodgings in Personal Retreat Availability
   ![selection_453](https://cloud.githubusercontent.com/assets/16792762/15774198/b660e7d4-2998-11e6-8e3a-9fee2361ca3a.png)
   ![selection_454](https://cloud.githubusercontent.com/assets/16792762/15774262/1a4d7fc8-2999-11e6-9620-203ed80749f5.png)
   ![selection_455](https://cloud.githubusercontent.com/assets/16792762/15774496/42c9e2ce-299a-11e6-9dad-ebc5f6e0e798.png)
2. Check in Office UI > On this Date Reservation Created 'Katie Stephens's shared Jun 8-9, 2016 Personal retreat reservation'

**Comment by neerajkhatri-btc** [comment]
@NishantUpadhyay-BTC : this issue is fixed.

**Comment by neerajkhatri-btc** [comment]
@NishantUpadhyay-BTC : 
1. Check in office UI BATH CABIN and NON BATH CABIN available for Reservation for Dates : Thu, 6-23-16
   ![selection_028](https://cloud.githubusercontent.com/assets/16792762/16142881/cd940d3e-3486-11e6-8f4b-032d0196cdf1.png)

Actual - It would Displaying Occupied in Availability Table in Pink.
Expected - It should Displaying Available in Availability Table in green.

**Comment by neerajkhatri-btc** [comment]
@NishantUpadhyay-BTC : 

1.In Availability Table show 'LODGE ROOM' and Breitenbush Tent,Your Tent,Personal Vehicle Site available this Date but actual see in this date 'Tue - 6-28-16' it will no available in available lodgings in Personal Retreat Availability
![welcome to breitenbush 2016-06-21 22-42-22 1](https://cloud.githubusercontent.com/assets/16792762/16239261/ae7e1254-3801-11e6-9657-6ccabd58e818.png)
![welcome to breitenbush 2016-06-21 22-42-51 2](https://cloud.githubusercontent.com/assets/16792762/16239262/ae8072ec-3801-11e6-8684-7fa18fa4bbe4.png)

Actual - It would Displaying Available in Availability Table in Pink.
Expected - It should Displaying Occupied in Availability Table in green.

**Comment by NishantUpadhyay-BTC** [comment]
This is related to #319 So I am closing it.
