### ISSUE TITLE
application breaks while click on yes in pv site's warning popup 

### ISSUE THREAD

**Issue by ManojParmar-BTC** [NishantUpadhyay-BTC/BLISS-Issue-Tracking#280]
steps to reproduce:
1. check availability page:
2. inputs arrival date: 15 nov 2016 
3. no of nights: 2
4. GP: true
5. click on check availability button and than click on reserve now button of pv sites.
6. than click yes for displayed popup.

![github 1](https://cloud.githubusercontent.com/assets/19205280/15886504/1a6733e2-2d7b-11e6-8b6c-b99c36666521.png)

**Comment by neerajkhatri-btc** [comment]
@NishantUpadhyay-BTC : this issue is fixed.
