### ISSUE TITLE
#1360 -  Guest UI: Missing Rate error on "Reserve Now" 

### ISSUE THREAD

**Issue by NishantUpadhyay-BTC** [NishantUpadhyay-BTC/BLISS-Issue-Tracking#288]
Currently the missing rate error ("Oops! It looks like we forgot to set the rate for this lodging! Please call our reservations office at 503.854.3320 to reserve.") only comes up once the user has logged in. Can this come up as soon as they click "Reserve now"?

**Comment by neerajkhatri-btc** [comment]
@NishantUpadhyay-BTC : this issue is fixed.
