### ISSUE TITLE
#1364 - Guest UI: Guest Details: Gender Unknown error erases guest names 

### ISSUE THREAD

**Issue by NishantUpadhyay-BTC** [NishantUpadhyay-BTC/BLISS-Issue-Tracking#289]
I was just booking a reservation for four guests. I entered all names on the guest details page, but intentionally left all gender blank. I got the expected error asking me to please choose gender for all guests - but the app erased all the guest names! Possible to keep these?

**Comment by NishantUpadhyay-BTC** [comment]
I noticed this in the Office UI/Details page, too. Can you also correct this issue there?

**Comment by neerajkhatri-btc** [comment]
@NishantUpadhyay-BTC : this issue is fixed.
