### ISSUE TITLE
#1361 - Office UI: Locking Lodgings: already locked message

### ISSUE THREAD

**Issue by NishantUpadhyay-BTC** [NishantUpadhyay-BTC/BLISS-Issue-Tracking#290]
Currently when a user attempts to lock a lodging that is already locked on another date, those dates and the lock note appear in the appropriate fields of the lock dialog. I'm assuming the reason for this is that any given lodging can only be locked for a single date range.

If that is correct, then please add the following message to the lock window whenever this condition is present:

"This lodging is already locked by <username> for the dates listed below. Lodgings can only be locked for a single date range, so if you choose to lock this lodging for another date range it will remove the previous lock. Please check with <username> before doing this."

If, on the other hand, my assumption above is incorrect, then please let me know why we are populating those fields with the other lock dates. Thanks!

**Comment by neerajkhatri-btc** [comment]
@NishantUpadhyay-BTC : this issue is fixed.

**Comment by NishantUpadhyay-BTC** [comment]
The second user reference is not populating: "... Please check with < user > before doing this."

**Comment by neerajkhatri-btc** [comment]
@NishantUpadhyay-BTC : this issue has been fixed.
