### ISSUE TITLE
#1363 Guest UI: "Cancel and Return..." button - generates "No Available Lodgings" error 

### ISSUE THREAD

**Issue by NishantUpadhyay-BTC** [NishantUpadhyay-BTC/BLISS-Issue-Tracking#291]
Twice now I've cancelled a reservation in progress by clicking on the "Cancel and Return to Availability" button. Both times, I've been returned to the "Personal Retreat Availability" page with the error: "No lodgings found for your matching requirements." displayed in red at the top of the screen. This error should not be displaying at this point.

**Comment by neerajkhatri-btc** [comment]
@ManojParmar-BTC :  Step for reproduce this issue
1. Enter this date and click 'non - plumbing cabin and reserve now' button
   ![welcome to breitenbush 2016-06-16 10-48-57](https://cloud.githubusercontent.com/assets/16792762/16106200/1686a6d2-33b0-11e6-9399-c89811d8bbb4.png)
2. On Guest Info. page click 'Cancel and return to availability' button 
   ![welcome to breitenbush 2016-06-16 10-49-13](https://cloud.githubusercontent.com/assets/16792762/16106202/168bafa6-33b0-11e6-8790-fb81300760ed.png)
3. The "Personal Retreat Availability" page with the error: "No lodgings found for your matching requirements." displayed in red at the top of the screen. 
   ![welcome to breitenbush 2016-06-16 10-49-19](https://cloud.githubusercontent.com/assets/16792762/16106201/168b34ea-33b0-11e6-9745-67b220834927.png)

Expected - This error should not be displaying at this point.

**Comment by neerajkhatri-btc** [comment]
@NishantUpadhyay-BTC : this issue is fixed.
