### ISSUE TITLE
 #1365 - Guest UI: Payment Screen: Need cancel buttons 

### ISSUE THREAD

**Issue by NishantUpadhyay-BTC** [NishantUpadhyay-BTC/BLISS-Issue-Tracking#293]
On the Payment Screen (where we're taking CC info) we need some cancel buttons:

Return to Summary Page
Return to Guest Details Page
Cancel Reservation and Return to Availability

**Comment by neerajkhatri-btc** [comment]
@NishantUpadhyay-BTC : this issue is fixed.
