### ISSUE TITLE
#1244 -  Office UI: +65 Discount generates many zeros in Payment screen 

### ISSUE THREAD

**Issue by NishantUpadhyay-BTC** [NishantUpadhyay-BTC/BLISS-Issue-Tracking#305]
It looks like we fixed the symptom, but not the cause. The issue is actually happening in the way the 10% discount is being calculated and applied. The app is applying the discount fractionally - i.e. in amounts that are not rounded to the nearest dollar. We've set the payments to _display_ whole amounts, but the fractional amount remains in the background. This results in fractional negative balance due amounts that cannot be displayed accurately, i.e. they show up as -$0.00, when the actual amount due is more like -$0.0025. There is no way to see this and no way for the payments engine to apply a payment of less then one penny. The end result is that we end up with balance dur reservations piling up in our To Do list, but with no obvious way to clear them out. I actually found a workaround for this and applied it on staging for tests today, but you can see this in action in Production with the following reservation IDs: 78694, 82276, 80537 and others. If you check the same res IDs on staging you'll see what I did as a workaround: I changed all ages to 17-64, then applied the senior discount manually using the "Other" field. Because this issue is happening on Production, it's freaking out a lot of the office staff, so we really want to get this issue addressed quickly, please.

**Comment by neerajkhatri-btc** [comment]
@NishantUpadhyay-BTC : this issue is fixed.
