### ISSUE TITLE
#1373 - Office UI: Locking Lodgings: Feedback on no lock note 

### ISSUE THREAD

**Issue by NishantUpadhyay-BTC** [NishantUpadhyay-BTC/BLISS-Issue-Tracking#306]
Please add friction of some kind to let the user know that the Lock Note is a required field when a user attempts to lock a lodging without entering a lock note. This could be a popup window or a message that comes up in the lock window itself. Either way, the message should keep the lock window up.

Currently if the user attempts to lock the lodging without entering a lock note, the lock window closes on save and nothing happens - the lodging is left unlocked and the user receives no feedback explaining why.

Just noticed that this actually _is_ generating feedback - at the top of the page, after closing the lock dialog. That's not really working as intended. The warning really needs to come up inside or over top of the lock dialog, without closing the lock dialog.

**Comment by neerajkhatri-btc** [comment]
@NishantUpadhyay-BTC : this issue is fixed and verified on staging.
