### ISSUE TITLE
#1372 - Office UI: Admin/Special Times: Special times need to "end" at 3PM 

### ISSUE THREAD

**Issue by NishantUpadhyay-BTC** [NishantUpadhyay-BTC/BLISS-Issue-Tracking#307]
It should be possible to make a reservation with conflicting party members on the _last_ day of an Adult Only or Gender Specific time period.

Example:
If we have a women's only time period set up for June 24th - 26th, it should be possible for us to make a reservation that starts on June 26th for a party that contains men. The reason for this is that the Women's Only time ends at 3PM on the last day. Reservations that begin on that day don't start until 3PM - so the Women's Only time is completed and there is no violation. The same is true for Adult Only and "Special" time periods.

**Comment by neerajkhatri-btc** [comment]
@NishantUpadhyay-BTC : this issue is fixed and verified on staging.

**Comment by NishantUpadhyay-BTC** [comment]
I also should have specified that these periods also begin at 3PM - so a reservation with gender/age conflicts should also be able to end on the first day of a special time with no warning or stop.

Example: During our testing yesterday, one of our users got a warning regarding a women only period on the PR Availability Page when she selected a number of nights that caused her reservation to end on the start day of a women only period. She shouldn't have gotten this warning, since her reservation is ending before the Women Only period actually begins.

**Comment by neerajkhatri-btc** [comment]
@NishantUpadhyay-BTC : this issue has been fixed.
