### ISSUE TITLE
#1371 - Office UI: Locking Lodgings: Unlocking a lodging while a reservation is open should not close the reservation

### ISSUE THREAD

**Issue by NishantUpadhyay-BTC** [NishantUpadhyay-BTC/BLISS-Issue-Tracking#308]
Open a reservation.
Lock a lodging.
Unlock the lodging.
Reservation is closed - but it should not be. The reservation should stay open while we're locking and unlocking lodgings.

**Comment by neerajkhatri-btc** [comment]
@NishantUpadhyay-BTC : this issue is fixed.
