### ISSUE TITLE
#1370 - Office UI: Locking Lodgings: Unlocking a lodging sometimes takes user to Events Tab

### ISSUE THREAD

**Issue by NishantUpadhyay-BTC** [NishantUpadhyay-BTC/BLISS-Issue-Tracking#309]
This has happened to multiple users at today's testing and at the testing last month, but I've been unable to duplicate it on my own. Apparently the issue arises after a particular user has been testing the locking function for a while -locking cabins, adding guests, removing guests, unlocking cabins, etc. At some point, whenever that user unlocks a locked cabin, the cabin unlocks and the view switches to the Events Tab. This is a problem, as the user may have to navigate through a complex set of choices to re-recreate the view they wanted.

**Comment by neerajkhatri-btc** [comment]
@NishantUpadhyay-BTC : this issue is fixed.
