### ISSUE TITLE
Expected behaviour after first time login

### ISSUE THREAD

**Issue by NishantUpadhyay-BTC** [NishantUpadhyay-BTC/BLISS-Issue-Tracking#31]
On successful FIRST login (or after PW change request), go to Account Info Page first- before reservation - with notice - please confirm your information and a "Save and Continue" button

**Comment by HirenBhalani** [comment]
branch: hb_issue_31.develop

**Comment by NishantUpadhyay-BTC** [comment]
This is merged to develop branch

**Comment by neerajkhatri-btc** [comment]
@NishantUpadhyay-BTC : this issue is fixed.
