### ISSUE TITLE
#1369 -  Guest UI: Availability Page: Descriptive Text and Graphics Changes 

### ISSUE THREAD

**Issue by NishantUpadhyay-BTC** [NishantUpadhyay-BTC/BLISS-Issue-Tracking#310]
With the implementation of #1367, we need to make some changes to the text. Also we're going to make the reservation button and the camping tab a bit more obvious:

New descriptive text (centered):

Scroll through the dates below to check general availability for the next six months. <line break>
Click on any green "Available" square to begin a reservation for that date, or:<line break>

<button-centered> "Click Here to Begin a Reservation"

(In other words, change the button text to "Click here to Begin a Reservation" and center it below the new descriptive text).
## 

In addition, can we save some vertical space by getting the color codes and the "Gender/Adult?" legend text into the same horizontal space? I'm thinking this could work if we break the legend text across three lines instead of two, then shift the horizontal placement so that the text plus the color codes are centered in relationship to the page. We'd also like to move the "i" icon to the end of the first line. Thus:

We occasionally have time periods where attendance is limited by gender or age. (i) <line break>
These periods are indicated in the chart below as follows: <line break>
W = Women Only, M = Men Only, A = Adults (18 and over) Only
## 

Finally, the camping tab needs to be more obviously a second tab. I like the design as it is, but people keep missing that it's there. Ideas? I was thinking perhaps we could outline both tabs, then use background color to denote the active tab. Perhaps use the same background and text colors that are used in Progress Bar?

**Comment by neerajkhatri-btc** [comment]
@NishantUpadhyay-BTC : this issue is fixed.
