### ISSUE TITLE
#1391 - Guest UI: Personal Retreat Availability Page: Bigger calendar icon for Date Selection

### ISSUE THREAD

**Issue by NishantUpadhyay-BTC** [NishantUpadhyay-BTC/BLISS-Issue-Tracking#312]
During SSHR testing, a few people mentioned that the calendar icon for Arrival Date was too small. Can we make it bigger to occupy more of the available space in the box?

**Comment by neerajkhatri-btc** [comment]
@NishantUpadhyay-BTC : this issue is fixed.
