### ISSUE TITLE
1390 - Guest UI: Personal Retreat Availability Page: Change departure date appearance 

### ISSUE THREAD

**Issue by NishantUpadhyay-BTC** [NishantUpadhyay-BTC/BLISS-Issue-Tracking#313]
Some users try to enter their departure date, as it looks just like all the other fields and so they think this is editable. Lets change that so it displays like fixed text - no white box around it.

**Comment by neerajkhatri-btc** [comment]
@NishantUpadhyay-BTC : this issue is fixed and verified on staging.
