### ISSUE TITLE
#1389 -  Guest UI: Personal Retreat Availability Page: Gender Help Text 

### ISSUE THREAD

**Issue by NishantUpadhyay-BTC** [NishantUpadhyay-BTC/BLISS-Issue-Tracking#314]
On the Personal Retreat Availability Page, please use the following for the Gender (i) help text:

“For the purposes of this initial availability query, we only need to know gender for solo reservations. While Breitenbush’s policy is to honor each person’s declared gender, we currently are able to provide only two gender options for you to choose from.”

**Comment by neerajkhatri-btc** [comment]
@NishantUpadhyay-BTC : this issue is fixed and verified on staging.
