### ISSUE TITLE
#1388 - Guest UI: Breitenbush Account Page: No Back Button Notice

### ISSUE THREAD

**Issue by NishantUpadhyay-BTC** [NishantUpadhyay-BTC/BLISS-Issue-Tracking#315]
The back button on the browser is disabled from the "Breitenbush Account Page" but clicking the browser's back button does not bring up the disabled notice. I'm using Chromium.

**Comment by neerajkhatri-btc** [comment]
@NishantUpadhyay-BTC : this issue is fixed.
