### ISSUE TITLE
#1384 -  Guest UI: Dorm Cabins still showing as available, still getting reserved 

### ISSUE THREAD

**Issue by NishantUpadhyay-BTC** [NishantUpadhyay-BTC/BLISS-Issue-Tracking#317]
Please see Res ID: 83064 and 83065 on staging. There were made via the Guest UI, and the app booked in D8 (Dorm). This lodging should not have shown as available, should not have come up in Available Lodgings list and this reservation should not have been possible via the Guest UI.

**Comment by neerajkhatri-btc** [comment]
@NishantUpadhyay-BTC : this issue is fixed.
