### ISSUE TITLE
#1377 -  Guest UI: Available Lodgings List: Lodge Rooms not showing up. 

### ISSUE THREAD

**Issue by NishantUpadhyay-BTC** [NishantUpadhyay-BTC/BLISS-Issue-Tracking#319]
In our testing on 6/22, from PR Availability we chose several dates/options that should have shown a Lodge Room as available, but that Lodging Type was never listed.

**Comment by neerajkhatri-btc** [comment]
@NishantUpadhyay-BTC : this issue is fixed.
