### ISSUE TITLE
Text changes in Guest details page

### ISSUE THREAD

**Issue by NishantUpadhyay-BTC** [NishantUpadhyay-BTC/BLISS-Issue-Tracking#32]
Guest Details:
- [x] Commonly Asked Questions - no link?  Also change text to "Frequently Asked Questions"
- [x] Agreements: Change text of the second sentence at the top to read: "We ask that you please carefully read each agreement and indicate your willingness to abide by them by checking the box to the left of each one."

**Comment by NishantUpadhyay-BTC** [comment]
This issue is fixed and available in 25_2_issue_27.develop branch

**Comment by NishantUpadhyay-BTC** [comment]
This is merged in develop branch

**Comment by neerajkhatri-btc** [comment]
@NishantUpadhyay-BTC : this issue is fixed.
