### ISSUE TITLE
#1376 -  Guest UI: Guest Details: Linens not always showing up when #guests = 1 

### ISSUE THREAD

**Issue by NishantUpadhyay-BTC** [NishantUpadhyay-BTC/BLISS-Issue-Tracking#320]
1. Without logging in, check availability, find a date, start a new reservation for one person and choose a lodging to reserve.
2. Log in as any test guest.
3. On the guest details page, primary guest has no linen option.
4. Now choose "Cancel and return to Availability"
5. From PR availability page, do not change any search options - just click on "search for available lodgings", and choose the same lodging type again.
6. On the Guest Details page you'll see that the Primary Guest now has the option to choose linens.

**Comment by neerajkhatri-btc** [comment]
@NishantUpadhyay-BTC : this issue is fixed.
