### ISSUE TITLE
#1375 -  Guest UI: Reservation timer dropping leading zero when seconds < 10 

### ISSUE THREAD

**Issue by NishantUpadhyay-BTC** [NishantUpadhyay-BTC/BLISS-Issue-Tracking#321]
Watch the reservation timer. Whenever seconds are < 10, the leading zero drops (e.g. 29:09 looks like 29:9).

**Comment by neerajkhatri-btc** [comment]
@NishantUpadhyay-BTC : this issue is fixed and verified on staging.
