### ISSUE TITLE
#1396 -  Guest UI: PV Site Warning: Change Button Text 

### ISSUE THREAD

**Issue by NishantUpadhyay-BTC** [NishantUpadhyay-BTC/BLISS-Issue-Tracking#328]
For the warning about PV site length, there are two buttons "No" and "Yes". Please change these to:
"Yes - Continue with my Reservation"
and
"No - Return to Available Lodgings"

**Comment by neerajkhatri-btc** [comment]
@NishantUpadhyay-BTC : this issue is fixed.
