### ISSUE TITLE
#1395 - Guest UI: Availability displaying differently for camping in Availability Page vs Availability Pop-Up

### ISSUE THREAD

**Issue by NishantUpadhyay-BTC** [NishantUpadhyay-BTC/BLISS-Issue-Tracking#329]
![screen shot 2016-07-06 at 5 25 19 pm](https://cloud.githubusercontent.com/assets/6542029/16642798/ec1ab50a-442b-11e6-9412-0c1749682555.png)
 Go to the Availability page and look at camping availability for July. Note that there is very little availability for PV sites.

Now go to the Personal Retreat Availability page, click on the "Check Calendar Again" and look at the same dates displayed in the pop-up. Different information is displayed.

**Comment by neerajkhatri-btc** [comment]
@NishantUpadhyay-BTC : this issue is fixed.
