### ISSUE TITLE
Display full cabin name on Thank you page

### ISSUE THREAD

**Issue by NishantUpadhyay-BTC** [NishantUpadhyay-BTC/BLISS-Issue-Tracking#33]
Thank You page: 
- [x] Lodging: Cabin? Should list specific lodging (Non-plumbing cabin, Lodge Room, etc.)

**Comment by NishantUpadhyay-BTC** [comment]
This issue is fixed and available in branch **25_2_issues_33.develop**

**Comment by NishantUpadhyay-BTC** [comment]
This is merged to develop branch

**Comment by neerajkhatri-btc** [comment]
@NishantUpadhyay-BTC : this issue is fixed.
