### ISSUE TITLE
#1394 -  Guest UI: Breitenbush Account Page: Need descriptive text 

### ISSUE THREAD

**Issue by NishantUpadhyay-BTC** [NishantUpadhyay-BTC/BLISS-Issue-Tracking#330]
Please add the following descriptive text to the Breitenbush Account page, just below the Progress Bar, as with other pages:

"To continue with your reservation online, you'll need to log in to your user account. If you already have a user account, please enter your login information using the fields on the left. Otherwise, if you've made an overnight reservation with us before, then you can create a new user account by entering the email address you used for that reservation in the field on the right." If you have never made an overnight reservation with us, then please call our reservations office at 503.854.3320 to make your first reservation."

**Comment by neerajkhatri-btc** [comment]
@NishantUpadhyay-BTC : this issue is fixed.
