### ISSUE TITLE
#1388 -  Guest UI: Breitenbush Account Page: No Back Button Notice 

### ISSUE THREAD

**Issue by NishantUpadhyay-BTC** [NishantUpadhyay-BTC/BLISS-Issue-Tracking#332]
The back button on the browser is disabled from the "Breitenbush Account Page" but clicking the browser's back button does not bring up the disabled notice. I'm using Chromium.

I'm still not seeing the message. FYI I'm using Chromium Version 46.0.2490.86 (64-bit) on Mac OS 10.11.4.

**Comment by neerajkhatri-btc** [comment]
@NishantUpadhyay-BTC : this issue has been fixed.
