### ISSUE TITLE
#723 - Office UI: Reservations: Shared reserervation should throw error when gender is not known

### ISSUE THREAD

**Issue by NishantUpadhyay-BTC** [NishantUpadhyay-BTC/BLISS-Issue-Tracking#333]
If we try to make a new reservation into a shared cabin when either gender is not known, or gender of the guests do not match, then BLISS should throw an error, with option to override.

**Comment by neerajkhatri-btc** [comment]
@NishantUpadhyay-BTC : this issue has been fixed.

**Comment by NishantUpadhyay-BTC** [comment]
"Open "Test Guest (Female) 10/24 res. John first tried to add the user to C4 (where there is a res for a MALE) for 10/25 and 10/26 and got the friction message for different gender. He then trid to make a reservation for 10/24 and 10/25 (overlapping the MALE guest reservation) and it DID NOT give the friction warning. Same results with "No Gender" selected for "Test Guest (Female)".

**Comment by neerajkhatri-btc** [comment]
@NishantUpadhyay-BTC : this issue has been fixed.
