### ISSUE TITLE
#1366 -  Office UI: Person Edit: "Create Guest UI User" function 

### ISSUE THREAD

**Issue by NishantUpadhyay-BTC** [NishantUpadhyay-BTC/BLISS-Issue-Tracking#335]
We'd like a way for Office Team members to manually create Guest UI users from existing guest records. The simplest way I can think of is to add a "Create Guest User" button to the "People" window that comes up whenever we click on the "edit" link in a guest record (e.g., when we've "found" that guest via a Reservations/Availability? search or elsewhere. I think this button could exist just to the left of the current "Save" button.

When clicked, first the user would be presented with a confirm dialog, e.g. "Are you sure you want to create a Guest User from this Guest Record?" with options for cancel and continue. On continue, the app would perform exactly the same function as happens within the Guest UI when user clicks on "Create"- i.e. - a user record is created and an email sent to the specified email address.

Note to the BLISS team - we'll need to add policy here that we don't allow office workers to then change the password live over the phone. Passwords should only be sent via email, so the user always has to be able to log into their email account to get the password intended for that user.

**Comment by neerajkhatri-btc** [comment]
@NishantUpadhyay-BTC : this issue has been fixed.

**Comment by NishantUpadhyay-BTC** [comment]
The error message for missing email address has a spelling error. The word "blank" is spelled "balnk". Other than that, this feature appears to be working well.

**Comment by neerajkhatri-btc** [comment]
@NishantUpadhyay-BTC : this issue has been fixed.
