### ISSUE TITLE
#1381 -  Guest UI: Guest Details: Graphics/Layout and Text changes 

### ISSUE THREAD

**Issue by NishantUpadhyay-BTC** [NishantUpadhyay-BTC/BLISS-Issue-Tracking#336]
On the Guest Details page, a few people commented that this page was a bit confusing, and we’ve got a few requests for how to clear this up.

-Under the Progress Bar, we’d like to add the following explanatory text: “Please let us know the name, gender, and age of each guest in your party, as well as their needs for linens or special diet meals.”

-Below the explanatory text above, a few lines of text that let the user know what options they’ve chosen so far: Arrival Date, Departure Date, Number Of Nights, Number of Guests, Guaranteed Privacy or Willing to Share (NB this will need to update if they remove G.P. via the controls on this page). I’m hoping these can be arranged in such a way as to minimize the vertical space they take up.

-We’d like to have a bit make the delineation between the primary guest and additional guest(s) more obvious. So -we’d like to change the description of “Primary Guest” to “Primary Guest (You)”, then increase the vertical space between the Primary Guest section and the Additional Guest section, then add some kind of divider - perhaps a thin horizontal line (green… or brown… whatever you think looks best, Sherry). Or if you think there’s a more aesthetically pleasing way to accomplish this delineation, I’m open to seeing it. Again, we’d like to see a mockup of what this could look like before committing.

![guest-details](https://cloud.githubusercontent.com/assets/6542029/16679808/1560ce7c-4508-11e6-9b0b-56fc9facf237.jpg)

**Comment by neerajkhatri-btc** [comment]
@NishantUpadhyay-BTC : this issue is fixed.

**Comment by NishantUpadhyay-BTC** [comment]
Almost there...

 Please add a little more space before the Descriptive Text at the top.
 This needs to be set apart just a bit.

 Also add some space between the Primary Guest table and the Additional
 Guest table. It needs to be visually clear that these are separate
 sections.

**Comment by neerajkhatri-btc** [comment]
@NishantUpadhyay-BTC : this issue is fixed.
