### ISSUE TITLE
#1385 -  Guest UI: Rates and Info pop-ups - text and graphics changes. 

### ISSUE THREAD

**Issue by NishantUpadhyay-BTC** [NishantUpadhyay-BTC/BLISS-Issue-Tracking#337]
From my recent email to Sherry:

-People would like to see the the peak dates in the column heading for Peak Rates. Perhaps this could just be the dates without the days to save space, e.g.:

Peak

5-27-16 to 10-15-16
(Not sure how this would look in Mobile.)

-We need to add the Willing to Share/G.P. rate policy text, pref. right under the rate table: “If you are booking a cabin alone and have chosen “Willing to Share", you can expect to share a cabin with one other person of the same gender. The lodging rates for Guaranteed Privacy (G.P.) are doubled, except for mid-week during the Non-Peak season, when G.P. costs an additional $45/night. G.P. does not apply to Lodge Rooms, Platform Tents, Your Tent sites, and Personal Vehicle sites, as these lodgings are inherently private. ”

-We need to add a “Close” button next to the “Reserve Now” button. The “x” in the upper right is too subtle for a lot of folks - though you can keep it there.

![detail-popup](https://cloud.githubusercontent.com/assets/6542029/16679840/569533a6-4508-11e6-8481-0fb9e269c39e.jpg)

**Comment by neerajkhatri-btc** [comment]
@NishantUpadhyay-BTC : this issue is fixed.
