### ISSUE TITLE
#1380 - Guest UI: Personal Retreat Availability Page: Willing to Share/G.P. changes 

### ISSUE THREAD

**Issue by NishantUpadhyay-BTC** [NishantUpadhyay-BTC/BLISS-Issue-Tracking#338]
From my recent email to Sherry:

On the Personal Retreat Availability Page we need to make the Willing to Share and G.P. choice more explicit. So:

-Change the description above the Radio Buttons to: “Would you like to share your lodging, or pay more for Guaranteed Privacy”

-Right now the radio buttons for this choice default to “Willing to Share” - we’re going to change this to default to having no selection made, and make the choice required (guest has to choose one or the other to proceed).

-Whichever choice is made should bring up a popup explaining what this means - and the popups for these can contain essentially the same text from the current help mouseover, so :

for “Willing to Share” it should read: “If you are booking a cabin alone, you can expect to share with one other person of the same gender.”

and for G.P.: "“The lodging rates for Guaranteed Privacy (G.P.) are doubled, except for mid-week during the non-peak season, when G.P. costs an additional $45/night. G.P. does not apply to Lodge Rooms, Platform Tents, Your Tent sites, and Personal Vehicle sites, as these lodgings are inherently private. If you select G.P. in your search and choose one of these lodgings, G.P. will not be applied to the cost of your reservation.”

The popups should have one button: “OK” which closes that window and preserves their choice.

![availability-page](https://cloud.githubusercontent.com/assets/6542029/16679999/80ecea26-4509-11e6-83ab-461280920833.jpg)

**Comment by neerajkhatri-btc** [comment]
@NishantUpadhyay-BTC : this issue is fixed.

**Comment by NishantUpadhyay-BTC** [comment]
The system allowed me to search for available lodgings without specifying my choice. If # of guests = 1 then the user must choose either G.P. or Willing to Share before proceeding. Furthermore, if a user changes the # of guests then the G.P./Willing to Share option should be cleared.

One minor graphics change: the two radio buttons should be labeled: "Willing to Share" and "Pay More for Guaranteed Privacy"

**Comment by NishantUpadhyay-BTC** [comment]
Lets change the text for the popup note for "Willing to Share" so that it reads:

"If you are reserving a cabin for one person, you can expect to share with one other person of the same gender. You will not have to share your lodging if booking a Lodge Room, Platform Tent, Personal Tent or PV Site, or when reserving for more than one person.”

**Comment by neerajkhatri-btc** [comment]
@NishantUpadhyay-BTC : this issue has been fixed.
