### ISSUE TITLE
#1379 -  Guest UI: Available Lodgings List: Graphics Changes 

### ISSUE THREAD

**Issue by NishantUpadhyay-BTC** [NishantUpadhyay-BTC/BLISS-Issue-Tracking#339]
From my recent email to Sherry:

The Available Lodgings list needs some reworking. Right now this is displaying as a tabulated list. However, the header row contains titles for only the first column - Lodging Type. The other two columns have no explaination of what is being displayed, and in fact what gets displayed changes based on various search results. Sometimes the "Rates and Info” and “Reserve Now” buttons are displayed in these columns, and sometimes they aren’t - but instead we get information that explains why a particular lodging type can’t be reserved despite the fact that it shows as available in the Availability Table from the previous page. If we are going to keep displaying this information in a table, then I think we need to re-think how this is built: we need some kind of description in each of the column headers -and I think we ought to move explanatory messages over into the ‘Rates and Info” column instead of the “Reserve Now” column. But before we try those options, I’m wondering if there might be a cleaner, more intuitive and responsive way to display this data? Any ideas?

![availability-page](https://cloud.githubusercontent.com/assets/6542029/16680095/178d6ea6-450a-11e6-9807-18eeadb9097b.jpg)

**Comment by neerajkhatri-btc** [comment]
@NishantUpadhyay-BTC : this issue is fixed.
