### ISSUE TITLE
Problem in sending email

### ISSUE THREAD

**Issue by NishantUpadhyay-BTC** [NishantUpadhyay-BTC/BLISS-Issue-Tracking#34]
A reservation under my account (created with address paul@breitenbush.com) listed confirmation email as going to sehr@breitenbush.com - why?

**Comment by NishantUpadhyay-BTC** [comment]
@HirenBhalani-BTC Can you please add the reason why we have added this issue on hold?

**Comment by NishantUpadhyay-BTC** [comment]
@neerajkhatri-btc As per my understanding, client is talking about the "Thank you" page where in previous version, a static email id was there. We have changed it with current user's email address. So You can close it for now. If this is my misunderstanding then we will reopen it.

**Comment by neerajkhatri-btc** [comment]
@NishantUpadhyay-BTC : as per your comment so i close it.
