### ISSUE TITLE
#1386 - Guest UI: Site-Wide: Need a visual way to differentiate 'Primary" and "Secondary" or alternate buttons

### ISSUE THREAD

**Issue by NishantUpadhyay-BTC** [NishantUpadhyay-BTC/BLISS-Issue-Tracking#340]
Site Wide:
-We need to differentiate the look of the “Affirmative” (primary) and “Negative” or "alternate” navigation buttons. The primary button on each page ought to be the button that takes you to the next step of the reservation, and should be more prominent in some way than all other buttons on any given page. Perhaps Dark Green/Gray? Green that changes on mouse-over as we’ve done elsewhere? Or some kind of additional line around the primary? We’re interested in seeing a mockup of your ideas.

See attached from Sherry. We'll want this formatting wherever we have multiple choices, but one is the "default" or "preferred" choice. I imagine that these will function much like the Availability Table "camping" tab does now - such that the "greyed" buttons turn dark green on mouseover.

![screen shot 2016-07-07 at 8 57 43 am](https://cloud.githubusercontent.com/assets/6542029/16680152/57f0792a-450a-11e6-9ecd-e048a5614ef6.png)

**Comment by neerajkhatri-btc** [comment]
@NishantUpadhyay-BTC : this issue is fixed.
