### ISSUE TITLE
#1378 -  Guest UI: Availability Table: Graphics Changes 

### ISSUE THREAD

**Issue by NishantUpadhyay-BTC** [NishantUpadhyay-BTC/BLISS-Issue-Tracking#341]
From my recent email to Sherry, Amit, and Nishant.
First:
On the Availability Table - the first one with the red/green blocks - can we have additional rows that separate out the months? So, for instance, as I scroll through June and then get to July, the first row of July would be a different colored row that spans all rows (no cell divisions) with the word “July” centered. Possible? I’m thinking the row color might be the dark green that we’re using for buttons - or maybe the brown that we’re using in the table header row. Sherry - can you mock that up, please? We’ll also need to see how this looks in Mobile - when the table switches columns and rows. I’m thinking the month division would switch to a thin column division with the text orientation flipped sideways (i.e. turned counter-clockwise so read from the right)

Second:
Again in the Availability Table, our current solution for displaying Gender Only and Adult Only times is working OK (Capitol Letter corresponds to the special time type appearing in the Date Column), but some people found this non-intuitive or too subtle. We’re interested in exploring other ways we might indicate special times on the Availability Table. Here are some ideas: 1. Some kind of colored hash through all the boxes on that date- - 2. Have a phrase that spans across all rows on that date, e.g. “Adults Only", “Women Only”, “Men Only”. Other ideas from any of you? Again, Sherry - could you put together some visuals? We’ll need mobile views, too of course.

Third:
Again on the Availability Table, We’re running into confusion (which we all knew would happen) when users try to book a reservation for time periods that look like a particular lodging is available, but it turns out that actually only shared lodgings were available for one or more of the days of their reservation. We’ve programmed responses for some of these cases, but we’re coming up with more use cases that would be too cumbersome to work out. Our strong feeling here is that we need a way for the Availability Table to display differently when only shared lodgings are available for a particular type of lodging on a particular day. After much debate and brainstorming, the idea we’ve settled on is to use a third color: Yellow - which we’d like to present for these cases. This would also need to be added to the color key above. Again, Sherry - can you pick a yellow (or something like yellow) that you think looks good and mock this up.

And, now I think of it, Sherry - it would probably save you time and effort to just mock up one graphic of the Availability Table in desktop/mobile/iPad views that shows all the changes and options discussed above.

![availability-table](https://cloud.githubusercontent.com/assets/6542029/16680224/bedb5b8c-450a-11e6-97d0-ac1c8dc31ed5.jpg)

**Comment by neerajkhatri-btc** [comment]
@NishantUpadhyay-BTC : this issue is fixed.

**Comment by neerajkhatri-btc** [comment]
@NishantUpadhyay-BTC : this issue is fixed.
