### ISSUE TITLE
#1382 - Guest UI: Site-Wide: Need a visual way to indicate required fields 

### ISSUE THREAD

**Issue by NishantUpadhyay-BTC** [NishantUpadhyay-BTC/BLISS-Issue-Tracking#342]
From my recent email to Sherry:

Site-Wide: we need a visual way to indicate required fields, and need to add explanatory text to any page that has them. I’ve seen this done with asterisks, different stroke color on required field boxes, and different fill (highlight) color in required fields. 

Per Sherry, we're going to go with the standard red asterisk - see attachment. We'll also need a note on each page that contains required fields- perhaps under the descriptive text? : " \* = required field" 

![screen shot 2016-07-07 at 8 53 39 am](https://cloud.githubusercontent.com/assets/6542029/16680362/8756e7b6-450b-11e6-977b-2bcf5297bddb.png)

**Comment by neerajkhatri-btc** [comment]
@NishantUpadhyay-BTC : this issue is fixed.
