### ISSUE TITLE
#1397 Guest UI: Personal Retreat Availability Page: Text change 

### ISSUE THREAD

**Issue by NishantUpadhyay-BTC** [NishantUpadhyay-BTC/BLISS-Issue-Tracking#347]
Also, please add to the descriptive text:

"Begin your reservation by providing the following information (\* = required):"

**Comment by neerajkhatri-btc** [comment]
@NishantUpadhyay-BTC : This issue has been fixed.

**Comment by NishantUpadhyay-BTC** [comment]
Please change:
"Available lodgings will display after you've entered an arrival date and number of nights."

to

"Available lodgings will display after you complete the required fields above and click "Display Available Lodgings".

Also please increase the font size and make it bold. This needs to be significantly more obvious.

**Comment by neerajkhatri-btc** [comment]
@NishantUpadhyay-BTC : this issue has been fixed.
