### ISSUE TITLE
#1398-  Guest UI - Was able to book a shared reservation with incorrect gender 

### ISSUE THREAD

**Issue by NishantUpadhyay-BTC** [NishantUpadhyay-BTC/BLISS-Issue-Tracking#348]
Please see res ID 83491 on staging.

Note that I was able to make a shared reservation for a man in a cabin that was occupied by a woman. Obviously this should not be possible. Here's how I did it:

I was working on a reservation, logged in as guest030, which is male. I canceled that reservation and returned to availability. Then, when I did my next lodging search I came up with a lodging that was only available for share by the opposite gender. So I changed the gender to Female, ran the search again and reserved the shared lodging. I then completed the reservation as usual.

I'm unsure how to prevent this.

There are many places in the system were a user could intentionally bypass gender checks by "lying" about their gender. However, I think this particular case might be one we should specifically test against at the Guest Details screen. So in this case Guest030 as the Primary Guest showed up on the Guest Details screen as male. When I clicked on the "Continue" button, I expected the system to prevent me from making any further progress, because the primary guest gender did not match that of the share. Now, that wouldn't prevent the user from simply changing their indicated gender - but at least we'll have covered our bases and given them the warning.

So, can we add that check and warning please?

Any other ideas?

**Comment by neerajkhatri-btc** [comment]
@NishantUpadhyay-BTC : this issue has been fixed.
