### ISSUE TITLE
#1400 - Guest UI: Shared lodgings messages - check/change text

### ISSUE THREAD

**Issue by NishantUpadhyay-BTC** [NishantUpadhyay-BTC/BLISS-Issue-Tracking#349]
Wherever we refer to shared lodgings, we need to make sure that the language refers to shared reservations "for one person" rather than referring to and "individual" or a "single person". It's a language thing that causes confusion - and we just want to clear that up.

**Comment by neerajkhatri-btc** [comment]
@NishantUpadhyay-BTC : this issue has been fixed.
