### ISSUE TITLE
Confirmation Process change

### ISSUE THREAD

**Issue by NishantUpadhyay-BTC** [NishantUpadhyay-BTC/BLISS-Issue-Tracking#35]
Actually what needs to happen is that they are told they'll receive a confirmation email once the office team checks it and confirms (see below under Office UI - To Do)

**Comment by NishantUpadhyay-BTC** [comment]
@neerajkhatri-btc  This is fixed and deployed as a different issue. You can close this.

**Comment by neerajkhatri-btc** [comment]
@NishantUpadhyay-BTC : this issue fixed.
