### ISSUE TITLE
#1401 -  Guest UI: Guest Details- changes to "Your Reservation So Far" 

### ISSUE THREAD

**Issue by NishantUpadhyay-BTC** [NishantUpadhyay-BTC/BLISS-Issue-Tracking#350]
If any of the following conditions are met, then we do not need to see the "Wiling to Share" and "Guaranteed Privacy" columns:
- The reservation is for more than one person
- The reservation is for a lodging for which GP/Share is irrelevant: Bbush Tent, Your Tent, PV site, Lodge Room

**Comment by neerajkhatri-btc** [comment]
@NishantUpadhyay-BTC : this issue has been fixed.
