### ISSUE TITLE
#1402 - Guest UI: Personal Retreat Availability Page: Changes clear Available Lodgings List

### ISSUE THREAD

**Issue by NishantUpadhyay-BTC** [NishantUpadhyay-BTC/BLISS-Issue-Tracking#352]
The PR Availability page is causing some confusion, in that people are expecting that when they make any change to the search parameters, the Available Lodgings list should reflect those changes without having to click on the "Check for Available Lodgings" button. This is especially true when they go "Check Calendar Again" and choose a new arrival date. However, I don't think we want the Available Lodgings list to auto-refresh on changes, as I think that would be too resource intensive, and would make the PR page unavailable for too much time (correct me if I'm wrong here). So, a few possibilities here:

Minimally, we'd like for the Available Lodgings List to clear whenever a user chooses a new date from the Availability Pop-up.

Better would be if the Available Lodgings List could clear whenever a new Arrival Date is chosen - even manually.

Best would be if the Available Lodgings List could clear whenever any search parameter is changed.

**Comment by neerajkhatri-btc** [comment]
@NishantUpadhyay-BTC : this issue has been fixed.

**Comment by neerajkhatri-btc** [comment]
@NaiyaShah-BTC : 
1. without login > PR page > fill data like
   ![welcome to breitenbush](https://cloud.githubusercontent.com/assets/16792762/17364437/c7e0e646-599d-11e6-890d-5bafbfd8c9c6.png)
2. now we can enter > Email in footer and Tab > Available Lodgings List Should be clear
   ![welcome to breitenbush1](https://cloud.githubusercontent.com/assets/16792762/17364502/1c3996de-599e-11e6-9268-ae3249bf8b4d.png)

Expected - Without login > Enter > Email in footer > Available Lodgings List and  WILLING TO SHARE     and PAY MORE FOR GUARANTEED PRIVACY Radio button should not be clear

**Comment by neerajkhatri-btc** [comment]
@NishantUpadhyay-BTC : this issue has been fixed.

**Comment by neerajkhatri-btc** [comment]
@NishantUpadhyay-BTC : this issue has been fixed.
