### ISSUE TITLE
#1403 - Guest UI: Reservation Summary: Pluralize guest type when more than one

### ISSUE THREAD

**Issue by NishantUpadhyay-BTC** [NishantUpadhyay-BTC/BLISS-Issue-Tracking#353]
If there is more than 1 adult, type still reads "adult", e.g. a reservation with 3 adults reads "3 adult".  This should be pluralized when the number is greater than 1, e.g. "3 adults"

Same with children, teens, and toddlers.

I haven't checked this on the Thank You page, or in the "Your Reservation So Far" table - but the same ought to apply there as well.

**Comment by neerajkhatri-btc** [comment]
@NishantUpadhyay-BTC : this issue has been fixed.
