### ISSUE TITLE
#1404 -  Guest UI: Reservation Summary and Thank You Page: Move arrival note 

### ISSUE THREAD

**Issue by NishantUpadhyay-BTC** [NishantUpadhyay-BTC/BLISS-Issue-Tracking#354]
On the Reservation Summary and Thank You pages, please move the Arrival Note ("NOTE: You may arrive as early as 3 p.m. to use the Hot Springs’ facilities but your lodging will not be available for check-in until 4 p.m.") to be on the next line right below the Arrival Date/Time?.

**Comment by neerajkhatri-btc** [comment]
@NishantUpadhyay-BTC : this issue has been fixed.
