### ISSUE TITLE
Change title and Header

### ISSUE THREAD

**Issue by NishantUpadhyay-BTC** [NishantUpadhyay-BTC/BLISS-Issue-Tracking#36]
General:
- [x] Change tab title "Welcome to BLISS" - to "Welcome to Breitenbush"
- [x] Upper Left Corner of each page: HotSprings -shoudl be Breitenbush Hot Springs Reservations (or header from JVM).

**Comment by neerajkhatri-btc** [comment]
@NishantUpadhyay-BTC : this issue is fixed.
