### ISSUE TITLE
#1406 - Guest UI: Payments: Cancellation Policy: Paid in Full - language and behavior change

### ISSUE THREAD

**Issue by NishantUpadhyay-BTC** [NishantUpadhyay-BTC/BLISS-Issue-Tracking#361]
We need to add a case to the Cancellation Policy for when the user pays in full for single night vs. multiple night reservations, and change the language.

So, for a multi-night reservation, if the user pays in full, cancellation policy should read:

"Thank you for paying in full. The first night's stay of <deposit amount> is a non-refundable deposit. If you cancel and you give at least 7 days notice, you will be given a Breitenbush credit voucher for the amount of the deposit (minus a $20.00 processing fee) that is good for one year. The balance of your payment will be refunded to your credit card. If you cancel with less than 7 days notice, your deposit will be forfeited (but do call us right away if an emergency comes up).

For a single night reservation, paying in full, the cancellation policy should read:

"Thank you for paying in full. Your payment of <payment> is a non-refundable deposit. If you cancel and you give at least 7 days notice, you will be given a Breitenbush credit voucher for the amount of the deposit (minus a $20.00 processing fee) that is good for one year. If you cancel with less than 7 days notice, your deposit will be forfeited (but do call us right away if an emergency comes up)."

**Comment by neerajkhatri-btc** [comment]
@NishantUpadhyay-BTC : this issue has been fixed.

**Comment by NishantUpadhyay-BTC** [comment]
Here is the language for the four cases of reservations made within seven days:

Within seven days, Single Day

Pay deposit:
Your deposit of <payment> is a non-refundable deposit. Your reservation is within our 7-day cancellation period. If you have to cancel this reservation your deposit will be forfeit, but do call us right away if an emergency comes up. Your balance of <balance due> will be due on arrival.

Pay in Full:
Thank you for paying in full. Your payment of <payment> is a non-refundable deposit. Your reservation is within our 7-day cancellation period. If you have to cancel this reservation your deposit will be forfeit, but do call us right away if an emergency comes up.

Within seven days, Multi Day
Pay Deposit Only:
Your deposit of <payment> is a non-refundable deposit. Your reservation is within our 7-day cancellation period. If you have to cancel this reservation your deposit will be forfeit, but do call us right away if an emergency comes up. Your balance of <balance due> will be due on arrival.

Pay in Full:
Thank you for paying in full. The first night's stay of <payment> is a non-refundable deposit. Your reservation is within our 7-day cancellation period. If you have to cancel this reservation your deposit will be forfeit, but do call us right away if an emergency comes up. The balance of your payment will be refunded to your credit card.

**Comment by neerajkhatri-btc** [comment]
@NishantUpadhyay-BTC : this issue has been fixed.
