### ISSUE TITLE
#1405 - Guest UI: Agreements- more language changes

### ISSUE THREAD

**Issue by NishantUpadhyay-BTC** [NishantUpadhyay-BTC/BLISS-Issue-Tracking#362]
For the Agreements page, please make the following language changes:

NO PETS:
Change to:
"Breitenbush is a pet-free facility, including our parking lot."

BEDDING
Change to:
"Please bring your own bedding. All beds come with a fitted bottom sheet only. Bedding and towels are available for rent. If you would like to add linens to your reservation, please go back to the previous screen".

ELECTRICITY:
add the following sentence to the end:
"Cell phone and laptop chargers are OK.”

CAFFEINE
Change to:
"We do not serve caffeinated beverages, though you may bring your own (hot water and filters are provided).

**Comment by neerajkhatri-btc** [comment]
@NishantUpadhyay-BTC : this issue has been fixed.
