### ISSUE TITLE
#1407: Guest UI: Payment screen: additions

### ISSUE THREAD

**Issue by NishantUpadhyay-BTC** [NishantUpadhyay-BTC/BLISS-Issue-Tracking#363]
Two things to add to our payment screen:

 Above the top right corner of the Card Number field, a series of small
 icons to indicate the card types we accept: visa, mastercard, discover.

 Add to the descriptive text:
 "We do not save your credit card or Paypal information."

**Comment by neerajkhatri-btc** [comment]
@NishantUpadhyay-BTC : this issue has been fixed.
