### ISSUE TITLE
#1409: Guest UI: Personal Retreat Availability Page: Sharing details warning should highlight radio buttons

### ISSUE THREAD

**Issue by NishantUpadhyay-BTC** [NishantUpadhyay-BTC/BLISS-Issue-Tracking#364]
Please set up the sharing details warning much the way we've set up the Agreements warning - such that when the sharing details warning comes up, the sharing radio buttons are also highlighted.

**Comment by neerajkhatri-btc** [comment]
@NishantUpadhyay-BTC : this issue has been fixed.
