### ISSUE TITLE
#1410 - Guest UI: Personal Retreat Availability Page: Change "Check Available Lodgings" button text

### ISSUE THREAD

**Issue by NishantUpadhyay-BTC** [NishantUpadhyay-BTC/BLISS-Issue-Tracking#365]
Another change to the "Check Available Lodgings" button:

 Please change the text of the button to:

 "Display Available Lodgings"

**Comment by neerajkhatri-btc** [comment]
@NishantUpadhyay-BTC : this issue has been fixed.
