### ISSUE TITLE
#1411  Guest UI: Personal Retreat Availability Page: Special Times Messages 

### ISSUE THREAD

**Issue by NishantUpadhyay-BTC** [NishantUpadhyay-BTC/BLISS-Issue-Tracking#366]
When the user clicks a date in the Availability Table (or the Availability Table popup) that coincides with any special time (Adult, Gender Specific or "Special"), the app should display the message for that time as soon as it switches to the Personal Retreat Availability Page.

Additionally, if the user begins a query that does not touch a special time, but then changes either the arrival date or number of nights such that the reservation does touch a special time, then the associated message should be displayed.

**Comment by NishantUpadhyay-BTC** [comment]
Regarding the popup- I can see this working fine, but I would not want to show them the same popup over and over again every time they change their dates. If it's just a message at the top of the screen this is not such a problem. So you see - if I'm moving my dates around within the same time period I'll keep getting the same popup over and over... What do you think?

I just tested the popup from the Availability table. Looks great for reservations for today - but I just tried it for a time marked "Women Only" and it didn't come up - also didn't see a warning when I landed on the Personal Retreat Availability Page. The date I chose was August 28th - which is within a women-only time that goes from the 25th through the 29th.

**Comment by neerajkhatri-btc** [comment]
@NishantUpadhyay-BTC : this issue has been fixed.
