### ISSUE TITLE
#1413 -  Guest UI: Reservation Summary and Thank You Page: Include Comments 

### ISSUE THREAD

**Issue by NishantUpadhyay-BTC** [NishantUpadhyay-BTC/BLISS-Issue-Tracking#369]
On the Summary and Thank You pages, we need to include any comments the user has entered in the Guest Details page. These can appear below the Lodging and above the Charges.

This is just so the user knows these have been captured.

**Comment by neerajkhatri-btc** [comment]
@NaiyaShah-BTC : UI issue pls check that.
1. When including comments (255 characters) the user has entered in the Guest Details page.
   ![untitled8](https://cloud.githubusercontent.com/assets/16792762/17127956/eb2134bc-5326-11e6-9334-df5cdf5dde12.png)

**Comment by neerajkhatri-btc** [comment]
@NishantUpadhyay-BTC : this issue has been fixed.
