### ISSUE TITLE
First screen: Availability

### ISSUE THREAD

**Issue by NishantUpadhyay-BTC** [NishantUpadhyay-BTC/BLISS-Issue-Tracking#37]
- [x] From anywhere on the site, if a user clicks on "Check Availability or "Make a Reservation" they will navigate to a page that displays the Availability Table. 
- [x] At the top of this page is, of course, our typical header, with links back to the main site, etc. Since this is true of all the Guest UI pages, I won't mention it further.
- [x] Just under the header is introductory text TBD - but for now use: <strong/>Reservations and Availability</strong> Here you can check for general availability for the next six months. Click the link below to begin booking a reservation.
- [x] The Availability Table should contain all the information displayed on the table at http://www.breitenbush.com/reservations/availability.html - though JVM is going to need to design it in such a way that BoTree can code it to be portable. 
- [x] Only needs to display Two Weeks at time, but should be scrollable out to 6 monts.
- [ ] Button/Link below: "Continue to Book a Reservation" (if possible, we may want this button to be conditionally formatted, such that if a user has landed on this page from a link to "Check Availability" then the button text is "Book a Reservation" but if they've landed here from "Make a Reservation" then the text would be "Continue to Book a Reservation"

**Comment by NishantUpadhyay-BTC** [comment]
@neerajkhatri-btc  There are lots of changes after the time the issue was created. So I think all the above points are already addressed or somehow UI gets changes so please close this for now. We will reopen is some related thing comes up.

**Comment by neerajkhatri-btc** [comment]
@NishantUpadhyay-BTC : as per your comment so i close it.
