### ISSUE TITLE
#1414 Guest UI: Lodging Info language changes 

### ISSUE THREAD

**Issue by NishantUpadhyay-BTC** [NishantUpadhyay-BTC/BLISS-Issue-Tracking#370]
Please make the following changes to Lodging Info popups:

Platform Tent:
Change description to read: "The Breitenbush platform tents are approximately 10'x10' and come with 2 single 4” foam camp mattresses on the floor. We do not allow any fires, propane lanterns, stoves or generators."

Non-Plumbing Cabin
Change description to read: "All cabins have at least one double/full bed. Additional beds may include another double bed, a single bed, or bunk beds. If you would like to request specific bed configurations, please indicate this in the notes field on the ‘Guest Details’ page to follow. We will do our best to accommodate your request but cannot make any guarantees. Toilets, sinks and showers are available in a nearby bathhouse."

ALL lodging info popups:

Please change "Peak Dates" to "Peak Rate Dates"

Thank you.

**Comment by neerajkhatri-btc** [comment]
@NishantUpadhyay-BTC : this issue has been fixed.
