### ISSUE TITLE
#1416 -  Office UI: Payments: Changes to payments are not changing confirmation state 

### ISSUE THREAD

**Issue by NishantUpadhyay-BTC** [NishantUpadhyay-BTC/BLISS-Issue-Tracking#376]
This is a new bug since 6/22.

From our testers yesterday:
Go to user "A Cabin". Select Nov 7th res. Got o payment screen. Note that John had orignally taken a CC deposit and confirmed. He then voided the cc payment and it did not un-confirm the res. He then added a cash payment and it did not un-confirm the res. He voided that cash payment and again, it did not unconfirm the res. He tried a bunch other payment changes and nothing seemed to trigger the un-confirmation.

**Comment by NishantUpadhyay-BTC** [comment]
It seems to me that only actions that void, cancel or transfer a payment to another reservation should "un-confirm" that reservation. In other words, if a payment is in any way being removed. Any action that would add a payment to a reservation need not un-confirm it - e.g.: a payment transferred from another reservation.

**Comment by neerajkhatri-btc** [comment]
@NishantUpadhyay-BTC : this issue has been fixed

**Comment by NishantUpadhyay-BTC** [comment]
Office Team tested this today and apparently Partial Refunds and Manual Voids are not changing a confirmed reservation to unconfirmed.

**Comment by neerajkhatri-btc** [comment]
@NishantUpadhyay-BTC : For Partial Refund
1. Go to reservation : https://mandala.breitenbush.com:9443/reservations/completion/84666
2. In payments click on Partial Refund > enter 50 and select cash check
3. click on Partial Refund > not changing a confirmed reservation to unconfirmed.

**Comment by neerajkhatri-btc** [comment]
@NishantUpadhyay-BTC : For Manual Voids
1. Go to reservation :  https://mandala.breitenbush.com:9443/reservations/completion/84681
2. Click on Manual Voids > Pop-up open and click ok > not changing a confirmed reservation to unconfirmed.

**Comment by neerajkhatri-btc** [comment]
@NishantUpadhyay-BTC : this issue has been fixed.
