### ISSUE TITLE
#1418 - Guest UI: Mobile View: Available Lodgings Table Should be more obviously scrollable

### ISSUE THREAD

**Issue by NishantUpadhyay-BTC** [NishantUpadhyay-BTC/BLISS-Issue-Tracking#377]
I think we need to make the same sort of tweaks here that we did for the Availability Table in Mobile. This confused everyone who tested on Mobile yesterday- -they couldn't tell that the info for available lodgings required scrolling across and down.

**Comment by neerajkhatri-btc** [comment]
@NishantUpadhyay-BTC : this issue has been fixed.
