### ISSUE TITLE
Second Screen: Data Entry plus Available Lodgings List

### ISSUE THREAD

**Issue by NishantUpadhyay-BTC** [NishantUpadhyay-BTC/BLISS-Issue-Tracking#38]
- [x] Reservation Data Entry Fields above, Available Lodgings List below.
- [x] Data entry fields exactly as we've already developed from the original design for the first page (Availability). 
- [x] Initially the Available Lodgings List will be blank, with overlay message "Available lodgings will display after you've entered an arrival date and number of nights."
- [x] Upon data entry and hit "Check Availability" the Lodging List populates: NOTE: only ONE listing per available lodging type is needed (e.g. - if there are multiple plumbing cabins available, we only need to list that option once).

**Comment by NishantUpadhyay-BTC** [comment]
This is implemented in 25_2_issues_38_39.develop branch

**Comment by NishantUpadhyay-BTC** [comment]
This is merged in develop branch

**Comment by neerajkhatri-btc** [comment]
@NishantUpadhyay-BTC : reopen issue. pls fix this.

**Comment by neerajkhatri-btc** [comment]
@NishantUpadhyay-BTC : this issue is fixed.
