### ISSUE TITLE
 #1421 - Office UI: Confirmation: Strange warning 

### ISSUE THREAD

**Issue by NishantUpadhyay-BTC** [NishantUpadhyay-BTC/BLISS-Issue-Tracking#380]
On staging o to "Test Guest (Female)". Go to res on 8/14 ("Running" event) - RES ID: 84553. Go to the Confirmation tab. Note you get a warning that says "Go ahead and confirm More Than two people in already reserved Lodging".

We don't see why you would get this warning.

**Comment by neerajkhatri-btc** [comment]
@NishantUpadhyay-BTC : this issue has been fixed
