### ISSUE TITLE
#1422 - Guest UI: Reservation Summary: Total Cost Info 

### ISSUE THREAD

**Issue by NishantUpadhyay-BTC** [NishantUpadhyay-BTC/BLISS-Issue-Tracking#381]
We'd like to add some text about the total cost on the Reservation Summary Page

Please place an asterisk next to total dollar amount, then under the cost breakdown, include the following text
"*Total cost includes all meals, taxes and daily well being programs."

**Comment by neerajkhatri-btc** [comment]
@NishantUpadhyay-BTC : this issue has been fixed.
