### ISSUE TITLE
#1425 -  Guest UI: Guest Details: Linens Dropdown -include costs. 

### ISSUE THREAD

**Issue by NishantUpadhyay-BTC** [NishantUpadhyay-BTC/BLISS-Issue-Tracking#384]
On the linens dropdown, it would be good for us to show the cost for each, as pulled from the rates table (i.e., so if we change the rate in the rate table, that change would be reflected here).

E.G

Individual ($18.00)
Couple ($24.00)

**Comment by neerajkhatri-btc** [comment]
@NishantUpadhyay-BTC : this issue has been fixed.
