### ISSUE TITLE
#1426 - Guest UI: Reservation Summary, Thank You Page, Printed Receipt: Addition to arrival note

### ISSUE THREAD

**Issue by NishantUpadhyay-BTC** [NishantUpadhyay-BTC/BLISS-Issue-Tracking#385]
Please add the following sentence to the Arrival note that appears under the arrival/departure times:

"When departing, you may remain on property until 3PM, but please clear out of your lodging by 1PM."

**Comment by neerajkhatri-btc** [comment]
@NishantUpadhyay-BTC : this issue has been fixed.
