### ISSUE TITLE
#1427 - Guest UI: Guest Details: Notice when age is under 12 years 

### ISSUE THREAD

**Issue by NishantUpadhyay-BTC** [NishantUpadhyay-BTC/BLISS-Issue-Tracking#386]
On the Guest Details page, when user selects age as 0-4, 5-10 or 11-16, present the following message as a pop up:

"Note: Children under 12 must be supervised by an adult at all times."

With a single button "OK" to dismiss.

Note that if they have multiple children in the party, it would be nice if they only see this message once.

**Comment by neerajkhatri-btc** [comment]
@NishantUpadhyay-BTC : this issue has been fixed.
