### ISSUE TITLE
#34 - Office UI: Users: User object can hash, store and compare passwords

### ISSUE THREAD

**Issue by NishantUpadhyay-BTC** [NishantUpadhyay-BTC/BLISS-Issue-Tracking#388]
Passwords are stored in the database as a hash. User object needs to take salt from system configuration yaml, and be able to convert password clear text into a one way hash so that it can be compared and confirmed as valid without revealing it.

**Comment by neerajkhatri-btc** [comment]
@NishantUpadhyay-BTC : this issue has been fixed.
