### ISSUE TITLE
#1415 -  Guest UI: Improve security of guest user passwords 

### ISSUE THREAD

**Issue by NishantUpadhyay-BTC** [NishantUpadhyay-BTC/BLISS-Issue-Tracking#389]
See ticket #388 , which covers this issue for the Office UI.

**Comment by neerajkhatri-btc** [comment]
@NishantUpadhyay-BTC : this issue has been fixed.

**Comment by NishantUpadhyay-BTC** [comment]
The language in the green confirmation that appears at the top of the Login Page needs to be changed to:
"An account confirmation email has been sent to < address >. Please follow the link in that email to confirm your account and continue with your reservation. Please check your spam filter if you do not see this email does not arrive in the next few minutes."

Also, on the account details page we need confirmation field for the password. This can behave just as it has in the Office UI - where both fields contain the hashed password that already exists, and if user changes they have to change both.

**Comment by neerajkhatri-btc** [comment]
@NishantUpadhyay-BTC : this issue has been fixed
