### ISSUE TITLE
Significant Change

### ISSUE THREAD

**Issue by NishantUpadhyay-BTC** [NishantUpadhyay-BTC/BLISS-Issue-Tracking#39]
We'd like to _greatly_ simplify the Available Lodgings List. We'd like to see them listed as a simple text table with three columns: Lodging Type, Rates and More Info (Button), Reserve Now (Button - OR optional text from the next bullet point below). We're ditching the pictures and ditching the Per-Night/Per Adult price listing in this table. Sherry, I'm wondering if there's a way to make this simple list look pretty? I leave that to you and Tom. This change is intended to assist with portability, and should also make for a cleaner interface that allows both the table and the data entry controls to display together on one page.

**Comment by NishantUpadhyay-BTC** [comment]
This is implemented in 25_2_issues_38_39.develop branch

**Comment by NishantUpadhyay-BTC** [comment]
This is  merged in develop

**Comment by neerajkhatri-btc** [comment]
@NishantUpadhyay-BTC : this issue is fixed.
