### ISSUE TITLE
#1428 -  Office UI: User Record: Phone Number format validation too strict 

### ISSUE THREAD

**Issue by NishantUpadhyay-BTC** [NishantUpadhyay-BTC/BLISS-Issue-Tracking#393]
I think we've been here before on the Guest UI -

If the phone number entered in the field does not conform to validation format, then the radio button for "preferred" cannot be selected. I think the problem is with validation on these fields. Apparently the Office Team has been using them to also enter extension numbers, e.g.: 503-854-3320 x138 - which the UI will not accept. Other than the occasional mis-type, what is the risk of just removing all validation other than a length limit (say, 20 characters) for these fields?

**Comment by neerajkhatri-btc** [comment]
@NishantUpadhyay-BTC : this issue has been fixed.

**Comment by neerajkhatri-btc** [comment]
@NishantUpadhyay-BTC : this issue has been fixed.
