### ISSUE TITLE
#1429 - Office UI: Shared Cabin Gender Warning Language Chnage 

### ISSUE THREAD

**Issue by NishantUpadhyay-BTC** [NishantUpadhyay-BTC/BLISS-Issue-Tracking#394]
Current language for this warning is:

"You are trying to reserve an already reserved lodging with opposite gender in it. Click OK to continue."
with two buttons: OK and Cancel

Please change to:

"You are trying to reserve a shared lodging for a party who's gender is either unknown or does not match the gender of the party in the existing reservation for that lodging. Click "OK" to proceed with this reservation as is, or "Cancel" to back out. "

**Comment by neerajkhatri-btc** [comment]
@NishantUpadhyay-BTC : this issue has been fixed
