### ISSUE TITLE
#1197 -  Office UI: Pre-rollout data cleaning 

### ISSUE THREAD

**Issue by NishantUpadhyay-BTC** [NishantUpadhyay-BTC/BLISS-Issue-Tracking#396]
Before we push the Guest UI to public beta there is some data cleaning that needs to be done on the guest records in the Office UI.

We want to make sure that the only guest users who can successfully create a login ID are guests that have actually stayed here. However, there are some existing guest records for people who didn't actually ever make it here. One example is a person calls in to make a reservation for the first time, but never ends up coming for various reasons. We create a guest record for them and begin making the reservation, but at some point they change their mind (not OK with nudity, not OK with remote location, etc.). We then cancel or delete the reservation - but the guest record remains. Someone who fits this category could potentially log in to the Guest UI and successfully book a reservation without ever having been here or spoken to anyone. We need to prevent this, so existing guest records that fall into this and other similar categories will need to be deleted.

The following is a list of conditions for deletion, as well as a list of exceptions:

Delete any record for which any of the following conditions apply:
-There are no reservations attached.
-There are only cancelled reservations attached.

Exceptions: Leave any record that fits the above criteria but which also:
-Is a record for any guest who is marked as "Banned" (many of these do not have reservations attached)
-Is a record for an event presenter (attached to an event). Some people have only been presenters, but have no reservation record.
-Leave the following "fake" guest records that we use as workarounds for various purposes: "Event Bedding", "Event Man", "Event Woman", "Check Availability", "Wait List", "Maintenance", "Deep Cleaning"

**Comment by neerajkhatri-btc** [comment]
@NishantUpadhyay-BTC : this issue has been fixed.
