### ISSUE TITLE
Guest UI : UI issue > Payment Summary > Billing Address  

### ISSUE THREAD

**Issue by neerajkhatri-btc** [NishantUpadhyay-BTC/BLISS-Issue-Tracking#399]
![untitled5](https://cloud.githubusercontent.com/assets/16792762/17693828/8579e2fa-63be-11e6-836a-270aabfe7f76.png)

Actual - when to reaching Payment Summary Page to enter Card, Month, Year, CVV, Zip Code, and press tab key then this issue occurs.

**Comment by NishantUpadhyay-BTC** [comment]
This issue is because of Grammarly extension. Please remove it and test.

**Comment by neerajkhatri-btc** [comment]
@NishantUpadhyay-BTC 👍
