### ISSUE TITLE
facing issue 'Lodging is Already Reserved. Please search again.' 

### ISSUE THREAD

**Issue by neerajkhatri-btc** [NishantUpadhyay-BTC/BLISS-Issue-Tracking#4]
![selection_052](https://cloud.githubusercontent.com/assets/16792762/12969762/5fe76662-d0ab-11e5-8e96-3d983480e049.png)

1.login with id and password
2.enter arrival date(07/09/2016) and enter no. of night =3, including guest = 2, minimum number of beds=2 and click check availability button.
3.available lodging = 2 select and click reserve
4.click user profile icon and update gender = male and click update button

**Comment by NishantUpadhyay-BTC** [comment]
@neerajkhatri-btc - This issue is fixed. Please confirm.

**Comment by neerajkhatri-btc** [comment]
@NishantUpadhyay-BTC : This issue is fixed
