### ISSUE TITLE
Signiicant Addition - In lodging list availability

### ISSUE THREAD

**Issue by NishantUpadhyay-BTC** [NishantUpadhyay-BTC/BLISS-Issue-Tracking#40]
if there are two different lodgings of the same type available for consecutive nights, but not availability for the same lodging for consecutive nights, display that lodging type with a message in the place where the "Reserve Now" button would be: "A reservation for a lodging of this type might be possible but, but would require a move that this system cannot yet accommodate. If you would like to try booking this lodging, please call our Reservations Office at 503.854.3320". Example: The Availability Table on the first page displays that there is a plumbing cabin available on both April 1 and April 2. However, what is being shown is that there are two _different_ plumbing cabins available - say, for instance, Cabin A1 is available 4/1 (but not on 4/2) and cabin A2 is available 4/2 (but not on 4/1). The current Availability Table has no way to distinguish this, and so a user might easily be lead to believe that they ought to be able to use this system to book a
 reservation for a plumbing cabin for those two nights. Without a message like the one described, the user might try to book this reservation and be frustrated and confused as to why the Plumbing Cabin does not display in the Available Lodgings list.

**Comment by neerajkhatri-btc** [comment]
@NishantUpadhyay-BTC : In availability table display lodging but  in check availability not displaying AVAILABLE LODGING

**Comment by NishantUpadhyay-BTC** [comment]
@neerajkhatri-btc This is fixed. Please test on staging.

**Comment by neerajkhatri-btc** [comment]
@NishantUpadhyay-BTC : this issue is fixed.
