### ISSUE TITLE
#1431 Guest UI: Temporary Changes for first Public Test 

### ISSUE THREAD

**Issue by NishantUpadhyay-BTC** [NishantUpadhyay-BTC/BLISS-Issue-Tracking#400]
When we push our first public test, we'll still be using the test server and dummy credit cards. We'd like to make some temporary changes to help guide testers through these steps. We'll be taking these changes down once our testing is complete.

First, on the Reservation Summary Page, just above the 'Pay Deposit" and "Pay In Full" buttons, we'll need a notice, in red text: "You will be given a test cc card number to use for payment. No actual charges will be made."

Second, also on the Reservation Summary Page- remove the PayPal? section - just to keep things simple for this test.

Third - on the Payment Page: Can this be set up to auto-fill the test cc numbers? If so, then all we'll need on this page is a notice near the top that says - Test cc card info has been auto-filled for this testing session. Please just click on "Purchase" below.

**Comment by neerajkhatri-btc** [comment]
@NishantUpadhyay-BTC : this issue has been fixed.
