### ISSUE TITLE
#1432 - Guest UI: Login Screen: behavior on existing account 

### ISSUE THREAD

**Issue by NishantUpadhyay-BTC** [NishantUpadhyay-BTC/BLISS-Issue-Tracking#403]
Currently when user enters an email address for an account that has already been created as a guest user, the system replies with the "address found/create" dialog. But when user hits create, it fails with message: "Validation failed: Login has already been taken"

Instead. can we catch this error when the user inputs their email address and clicks "Setup"? - then present the message: A user account already exists for this email address. Please use the "Existing Account" fields on the left or choose "Forgot Password" if you cannot remember your account info."

**Comment by NishantUpadhyay-BTC** [comment]
I tested this the other day with furtherserene@gmail.com - which I knew to
 be an account that was already created - and got the behavior I described
 above.

 Today, I got a different behavior. First, I was presented with the
 successful message though I noticed that the language for successful
 creation reads:
 "An account confirmation email has been sent to furtherserene@gmail.com.
 Please follow the link in that email to confirm your account and continue
 with your reservation. Please check your spam filter if you do not see
 this email does not arrive in the next few minutes."

 The last sentence does not make sense. It should read:

 "Please check your spam filter if you do not receive this email in the
 next few minutes."

 I logged into my email for furtherserene@gmail.com, found the confirmation
 email, and clicked on the link (noting that the link was clickable... and
 in gmail- - so that's not consistent either- hmmm).

 Clicking me on the link took me to the Availability page with an error
 message: "User is already activated."

 So, this brings me back again to the request in my ticket description
 above.  We should be catching existing accounts right away when user
 enters an address in the "New Account" field.

**Comment by neerajkhatri-btc** [comment]
@NishantUpadhyay-BTC : this issue has been fixed.
