### ISSUE TITLE
#1436: Office UI: Person Record: "Needs Marketing Director Review" checkbox

### ISSUE THREAD

**Issue by NishantUpadhyay-BTC** [NishantUpadhyay-BTC/BLISS-Issue-Tracking#404]
We need the ability to mark guests who, while not "banned" have displayed
 issues that require us to check in with them before we allow them to come
 back. Typically this is done by the Marketing Director.

 So, could we please have a section in the Person Record edit, much like
 the "Banned" section, labeled, "M.D. Check-In Required"  - along with an
 "M.D.-Check" checkbox, the date and a notes field. Access to this feature
 should be only for users with Admin privileges.

 When this box is checked it will have two consequences:
1. If an OfficeUI user tries to book any kind of reservation, they will
   receive a pop-up message: "This guest must have a conversation with the
   Marketing Director before you can book this reservation." With two buttons
   "Cancel" (which cancels) and "We've had the conversation - continue to
   book." (which bypasses the block and continues the reservation - but does
   NOT uncheck the "M.D. Check" checkbox.
2. For the GuestUI, if this box is checked, then on new user creation
   they'll get the same message as banned users. If a user with an existing
   account then has this box checked after account creation, they'll get the
   message:
   "You must call our reservations office at 503.854.3320 before you can use
   this system."
   
   Come to think of it, #2 above should also be a case for what happens for a
   user with an existing Guest UI account who is later banned...

**Comment by neerajkhatri-btc** [comment]
@NishantUpadhyay-BTC : this issue has been fixed.
