### ISSUE TITLE
#1434: Office UI: New account Email: Confirmation link not always clickable

### ISSUE THREAD

**Issue by NishantUpadhyay-BTC** [NishantUpadhyay-BTC/BLISS-Issue-Tracking#407]
The confirmation link in the new account or password reset email is not
 always clickable. We've tested this in Apple Mail, Gmail and Yahoo, and so
 far the link has only been clickable in Apple Mail.  It would be nice to
 have this be more consistent, however I think it's also true that
 sometimes it will be impossible - for instance if the user has a mail
 service that only displays in plaintext.

 So two things: First, lets see if we can get the link hot for Gmail, Yahoo
 and other web-based email that will accept html. Second, lets also include
 the following language: "To complete your account setup..."<or>"To reset
 your account password...", "...click the link below, or copy and paste it
 into your browser's address bar."

**Comment by neerajkhatri-btc** [comment]
@NishantUpadhyay-BTC : The confirmation link in the new account or password reset email is not working in yahoo Mail. The user has a mail service that only displays in plain text.
1. Password Reset :
   ![nirajkhatri96 yahoo mail](https://cloud.githubusercontent.com/assets/16792762/18002629/90e27400-6ba6-11e6-84c8-b49daaa1a936.png)
2.  New account: 
   ![-1 unread manojparmar5606 yahoo mail](https://cloud.githubusercontent.com/assets/16792762/18002807/cdd4f508-6ba7-11e6-970c-9f14052d4bc4.png)

**Comment by neerajkhatri-btc** [comment]
@NishantUpadhyay-BTC : this issue has been fixed.
