### ISSUE TITLE
Office UI: Need to be able to re-confirm an event reservation for early departures

### ISSUE THREAD

**Issue by NishantUpadhyay-BTC** [NishantUpadhyay-BTC/BLISS-Issue-Tracking#411]
On production, please see res ID 86334. This is a case where an event
 guest left early and because we were able to fill that space, we granted
 that guest a refund after the fact. This sort of thing happens from time
 to time. We removed the guest from their cabin on the final day, set their
 departure date to one day earlier and applied the refund. We must do it
 this way for an event reservation, because we cannot simply shorten the
 reservation length for an event reservation, the way we can for PRs. The
 end result in this case was that we could not confirm the reservation, as
 there was an "unoccupied" cabin on the last day of the reservation. I
 managed a workaround for this by putting the guest into another cabin and
 then adjusting the lodging cost - but this will not always be possible and
 is not a good workaround. In this case, we needed to show their original
 lodging as unoccupied so we could put another guest in their place.  This
 needs to be addressed before our production push next Wednesday.

**Comment by neerajkhatri-btc** [comment]
@NishantUpadhyay-BTC : this issue has been fixed.
