### ISSUE TITLE
#1439 - Office UI - unable to remove/move guests within a reservation 

### ISSUE THREAD

**Issue by NishantUpadhyay-BTC** [NishantUpadhyay-BTC/BLISS-Issue-Tracking#412]
Please see resID 81073 (Teddy Basladynski) on production. Also related: 86508 (Jennifer Slack) and 86501 (Patricia Roberts).

Teddy's a presenter for the Mushroom Gathering event, and these often have several people in the reservation, just like this one does. We're trying to do something that we often do with these reservations: shift people around into new lodging in order to free up a lodging for a full-paying guest. In this case the goal was to move two people in Teddy's reservation to cabin B6, then put the guests who were in B6 into A2. The steps involved to do this are as follows:
1. Open the existing reservations for B6 for this event (Jennifer and Patricia above) and remove cabin B6 from that reservation.
2. Open Teddy's reservation for this event and add B6 to the reservation.
3. On the reservation details tab for Teddy, move the two party members from A2 to B6 by dragging them manually for each day of the reservation.
4. On the lodging screen for Teddy's reservation, remove A2.
5. Go back to Jennifer's reservation, add A2 and put her in that cabin. Do the same for Patricia. 

Done.

When I attempted this on Staging, all went as expected - no problems. However, when I try this on production I get the following errors:
1. Trying to add B6 in step 2 above fails with the error "Something went wrong..." and when I click on OK it kiks me out of the reservation entirely with the error "Invalid Request: there is no Reservation #2920575"
2. Cannot remove A2 in step 4. This results in an endless spinning wheel. 

Because this works in staging but not on production this leads me to believe that either something in the recent history of this reservation is causing a background conflict, or there is something causing ajax failures on production that is specific to the production instance. I believe a review of the logs from around 1:30-2PM today on both Euterpe and Thalia might reveal more. Or perhaps checking the reservation histories on production, then compare them to the same histories on staging and see where they diverge.

New behavior: Nicole just reported that also she cannot add any more guests to this reservation (81073). She wanted to change it from 12 to 13, but on change from the Lodging screen, she gets an endless spinny wheel graphic and BLISS reports an Ajax failure.

**Comment by neerajkhatri-btc** [comment]
@NishantUpadhyay-BTC : this issue has been fixed.
