### ISSUE TITLE
#1441 - Office UI - Problem cancelling a reservation 

### ISSUE THREAD

**Issue by NishantUpadhyay-BTC** [NishantUpadhyay-BTC/BLISS-Issue-Tracking#413]
Please see res ID87088 for Troy Conklin on production. There was an event scheduled which was cancelled and moved to a new date. This reservation was part of that event. We removed the lodging from the reservation and refunded the credit card payment. Then we tried to cancel the reservation, but could not - the cancel button was not active. We could also not confirm the reservation without any lodging. I fixed this by first changing the reservation type to "Staff", then saving, which allowed me to confirm with no lodging. I then went back and changed the reservation type back to "Normal" and saved. After that, the Cancel link was finally available, so I went ahead and cancelled the reservation.

**Comment by neerajkhatri-btc** [comment]
@NishantUpadhyay-BTC : this issue has been fixed.
