### ISSUE TITLE
#1447 -  Office UI: Presenter Fee Mystery 

### ISSUE THREAD

**Issue by NishantUpadhyay-BTC** [NishantUpadhyay-BTC/BLISS-Issue-Tracking#414]
Please see reservation ID 81061 on Production.

This is the reservation for the presenter. It was originally made for one adult, and the Event Coordinator manually "zeroed out" the presenter fee Payments/Adjustments?. Later, on October 17, another EC logged in and added two children and one adult to the reservation. Mysteriously, the presenter fee vanished altogether. The EC corrected this in the adjustment column as well.

This is a large concern. We often change party members in reservations, and if this is happening in other event reservations it's possible that office team personnel will not notice if the presenter fee vanishes. We will be losing quite a bit of money if this error goes unnoticed in other reservations.

**Comment by neerajkhatri-btc** [comment]
@NishantUpadhyay-BTC :  this issue has been fixed.
