### ISSUE TITLE
#1448 -  GuestUI/Office UI: Ignore gender when age = 0-4 

### ISSUE THREAD

**Issue by NishantUpadhyay-BTC** [NishantUpadhyay-BTC/BLISS-Issue-Tracking#415]
For gender-specific camps that are non adults-only, we allow our guests to bring their babies regardless of gender. Current gender validation rules prevent this.

**Comment by NishantUpadhyay-BTC** [comment]
Please see resID 87533 on staging.

I created this res for a woman with one child age 0-4 and got no errors. I made changes to the res (added last name) within the Office UI on staging and saved and also got no messages or errors - which is perfect. Then I went to the lodging screen and changed number of guests to 3 and saved - no messages (which is what I expected). Then I went back to the details screen and entered in first and last name but did NOT enter age or gender: BLISS threw an Application 500 error. This was at approximately 10:50AM PDT. I then used my browser's back button to return to the reservation. I set the age at 0-4 and gender to Male and clicked save with no further issues.

**Comment by neerajkhatri-btc** [comment]
@NishantUpadhyay-BTC : this issue has been fixed.
