### ISSUE TITLE
#1449 -  Guest UI: Changes to Availability Page 

### ISSUE THREAD

**Issue by NishantUpadhyay-BTC** [NishantUpadhyay-BTC/BLISS-Issue-Tracking#416]
Guests are getting confused by the Availability screen, thinking that they ought to see workshop availability here, too.

To help remedy this, please make the following changes to the Availability Page:

-Change the title to "Personal Retreat Availability" (Note: we realize that this will make the title the same as the existing "Personal Retreat Availability Page" but we think this is OK -even desirable, as it re-enforces the notion that these two pages are part of the same stage of the reservation process).

-In the blank space under the text "We occasionally have time periods where attendance is limited...", please add the following notice: This table shows lodging availability for personal retreats ONLY, but lodging may still be available for workshops and events (Thanksgiving, Winter Solstice and New Years). For informaiton about reserving lodging for a workshop or event please visit our workshop page < link = ​http://breitenbush.com/workshops/>.

Finally, the text for shared cabins is also causing confusion. Currently says "= Shared (Available for one person only)" please change this to "= Shared Cabins Only" with an "i" help note: "Shared cabins may be reserved by one person who is of the same gender as the person occupying the cabin."

**Comment by NishantUpadhyay-BTC** [comment]
OK - a few niggling details:
- For the "Shared Cabins Only" key, please adjust the indent so that the "O" in "Only" lines up with the 'S" in "Shared". 
- The text we've added in the paragraph above the Availability Table has pushed the table further down the page. Also this added text (Beginning with "This table shows..." needs to be visually separate from the original text. So: Please add a line of space between old text and the new, then shift the table back up so that the the vertical space between the color key and the table is restored.

**Comment by neerajkhatri-btc** [comment]
@NishantUpadhyay-BTC : this issue has been fixed.
