### ISSUE TITLE
#1442 -  Office UI: Administration: Special Periods: Make special times note field longer 

### ISSUE THREAD

**Issue by NishantUpadhyay-BTC** [NishantUpadhyay-BTC/BLISS-Issue-Tracking#417]
The EC's would like the special times note to be bigger so they can see more of the entered text. Just a guess: I think it could probably stand to be about 1/2 again as big without blowing out the right side margin...

 OK, I think there's still room for improvement here. The fields for the start/end dates could me _much_ smaller. Please make them just wide enough to fit the necessary characters for MM/DD/YYYY, then shift everything else over to the left to maintain current spacing. Once that's done, go ahead and stretch out the notes field all they way out 'till the right border lines up visually with the right border of the "users" tab.

**Comment by neerajkhatri-btc** [comment]
@NishantUpadhyay-BTC : this issue has been fixed.
