### ISSUE TITLE
#1453 - Office UI/GuestUI: Guest Details: When age = 0-4 set meals to "none" and do not include in meal counts

### ISSUE THREAD

**Issue by NishantUpadhyay-BTC** [NishantUpadhyay-BTC/BLISS-Issue-Tracking#418]
We do not charge meals for guests age 0-4. Currently BLISS applies standard default meals to these guests and Office Staff must manually remove these. Please change this so BLISS does not add meals to guests who's age = 0-4.

**Comment by neerajkhatri-btc** [comment]
@NaiyaShah-BTC : not yet fixed for Unknown age.

**Comment by neerajkhatri-btc** [comment]
@NishantUpadhyay-BTC : this issue has been fixed.
