### ISSUE TITLE
#1454 -  Guest UI: Payment Screen: remove language referring to PayPal 

### ISSUE THREAD

**Issue by NishantUpadhyay-BTC** [NishantUpadhyay-BTC/BLISS-Issue-Tracking#419]
Language on the Payment Screen currently reads:

"Payment screen: Please enter your payment information below to complete your reservation. We do not save your credit card or Paypal information"

Please remove the reference to PayPal?, since we're not taking these yet.

**Comment by neerajkhatri-btc** [comment]
@NishantUpadhyay-BTC : this issue has been fixed.
