### ISSUE TITLE
#1443 -  Guest UI: Adult Only/Gender Specific times not displaying in Availability Table 

### ISSUE THREAD

**Issue by NishantUpadhyay-BTC** [NishantUpadhyay-BTC/BLISS-Issue-Tracking#420]
We allow an opposite-gender reservation to _end_ on the first day or _start_ on the last day of a gender-specific camp. The availability page looks like a male could make a reservation for one night starting on the 1st. And in fact when I click on the 1st to start a reservation, I see no gender warning. When I search for available cabins as a male, I get no warning. When I select one of the available lodgings and click 'Reserve Now" I get no warning. But once I log in to my account (where I am specified as a male) I get the blocking message at the top "You are trying to make a reservation for a gender specific time...." This is incorrect. I should have gotten the warning as soon as I tried to search for a cabin for a male on Dec 1.

I see the problem though. If we display "Women Only" on the 1st, then it looks like I wouldn't be able to make a reservation for a male that ends on the 1st.

Would it be possible to have the Availability Talbe display Adult only and Gender only times differently on the first and last day of the period? So for instance on the first day: "Women Only Starts at 3PM." and on the last day "Women Only ends at 3PM."?

For the edge case where one event starts on the same day another ends, just show the message for the event that starts on that day.

**Comment by neerajkhatri-btc** [comment]
@NishantUpadhyay-BTC : this issue has been fixed.
