### ISSUE TITLE
#1458 -  GuestUI: Availability for Today not showing correctly 

### ISSUE THREAD

**Issue by NishantUpadhyay-BTC** [NishantUpadhyay-BTC/BLISS-Issue-Tracking#421]
There are only shared cabins available for today, but the Availability Table is showing green for both plumbing and non-plumbing cabins.

Perhaps the logic for reservations for today (have to call) is interfering somehow?

Anyway, this needs to be fixed, as guests are calling in expecting they can reserve a non-shared cabin for tonight.

**Comment by neerajkhatri-btc** [comment]
@NishantUpadhyay-BTC : this issue has been fixed.
