### ISSUE TITLE
ToDo list on Office UI

### ISSUE THREAD

**Issue by NishantUpadhyay-BTC** [NishantUpadhyay-BTC/BLISS-Issue-Tracking#43]
Currently incomplete reservations in progress appear here. Reservations should not appear here until guest is complete and paid, then office team confirms and sends email.

**Comment by HirenBhalani** [comment]
branch(office UI)  :  guest_ui_release.preflight-15

**Comment by neerajkhatri-btc** [comment]
@NishantUpadhyay-BTC : this issue is fixed.
