### ISSUE TITLE
Reservation>Payments>Zip code accepted character in office UI

### ISSUE THREAD

**Issue by neerajkhatri-btc** [NishantUpadhyay-BTC/BLISS-Issue-Tracking#45]

**Comment by NishantUpadhyay-BTC** [comment]
@neerajkhatri-btc  I think in US zip code may contains alphanumeric characters. So until we get feedback from Paul to restrict it to number only, Let's put this on hold.

**Comment by NishantUpadhyay-BTC** [comment]
@neerajkhatri-btc  Please close this issue as this behaviour is pre-existing and already verified by office team of BLISS

**Comment by neerajkhatri-btc** [comment]
@NishantUpadhyay-BTC : As per your comment so i close it
