### ISSUE TITLE
error show "2016-05-17 is not within the passed reservation's range: Block:76094 (Workshop:2794:(P)OSM (2016-05-20:2016-05-21)), 2016-05-20..2016-05-21"

### ISSUE THREAD

**Issue by neerajkhatri-btc** [NishantUpadhyay-BTC/BLISS-Issue-Tracking#47]
![selection_109](https://cloud.githubusercontent.com/assets/16792762/13352082/fc7ecab8-dcb0-11e5-98c6-d4f79b5aac56.png)

**Comment by NishantUpadhyay-BTC** [comment]
@neerajkhatri-btc We have reverted the changes which causes this error. You will not get this error anymore. So please close it. There is another issue which is open and related to this. So close it for now.

**Comment by neerajkhatri-btc** [comment]
@NishantUpadhyay-BTC : As per your comment so i close it
