### ISSUE TITLE
updating user party details through with user id

### ISSUE THREAD

**Issue by neerajkhatri-btc** [NishantUpadhyay-BTC/BLISS-Issue-Tracking#5]
![selection_047](https://cloud.githubusercontent.com/assets/16792762/12978150/2f612664-d0f5-11e5-8189-15ae39203029.png)

@nishantupadhyaybtc : pls check that issue.

Step 1: login id and password (id=hirenbhalani@outlook.com , password= 12121212)

Step 2: enter data in Personal Retreat Availability and click check availability button.

Step 3: reserve any AVAILABLE LODGING
Step 4: in guest information page click continue button.

**Comment by HirenBhalani** [comment]
This is on Hold, This error may occurs due to some manual update in user record.

**Comment by NishantUpadhyay-BTC** [comment]
@neerajkhatri-btc  Please try to reproduce it, I am unable to reproduce it. If you can't reproduce then please close. It might occur due to some data issue.

**Comment by neerajkhatri-btc** [comment]
@NishantUpadhyay-BTC : this issue is fixed.
