### ISSUE TITLE
Change Header footer as per new psd 

### ISSUE THREAD

**Issue by NishantUpadhyay-BTC** [NishantUpadhyay-BTC/BLISS-Issue-Tracking#51]
-After looking at the header and footer in place, as submitted by JVM, we're going to change this yet again. Tom is working with Sherry on this and we'll let you know what the next decision is on this as soon as we have the PSD files for you.

**Comment by neerajkhatri-btc** [comment]
@NishantUpadhyay-BTC : this issue is fixed.
