### ISSUE TITLE
Change Date format in Reservation Summary

### ISSUE THREAD

**Issue by NishantUpadhyay-BTC** [NishantUpadhyay-BTC/BLISS-Issue-Tracking#53]
-Reservation Summary page:
First Meal: dinner on  Thursday Jun 9
Last Lunch: saturday, Jun, 11 - should read: last meal: Lunch on Saturday, Jun 11

**Comment by neerajkhatri-btc** [comment]
@NishantUpadhyay-BTC : this issue is fixed.
