### ISSUE TITLE
Name change in Lodging type based on the facility

### ISSUE THREAD

**Issue by NishantUpadhyay-BTC** [NishantUpadhyay-BTC/BLISS-Issue-Tracking#54]
-Need to work on names of lodgings displayed in Available Lodgings LIst,  Detail Popup and Thank You page. Currently lodging names are being displayed such as: "Cabins with Plumbing and no dorm spaces". These lodging names should be: Plumbing Cabin, Non-Plumbing Cabin, Lodge Room, Platform Tent, Tent Site, Personal Vehicle Site).

**Comment by neerajkhatri-btc** [comment]
@NishantUpadhyay-BTC : this issue is fixed.
