### ISSUE TITLE
Js issue in date picker 

### ISSUE THREAD

**Issue by neerajkhatri-btc** [NishantUpadhyay-BTC/BLISS-Issue-Tracking#55]
![selection_113](https://cloud.githubusercontent.com/assets/16792762/13385965/e2dc80aa-decc-11e5-84e7-23ece21996da.png)

**Comment by NishantUpadhyay-BTC** [comment]
@neerajkhatri-btc  This is the default behaviour of datepicker. When there isn't enough space below text field then calendar popup will be displayed above the text field. You can close this.

**Comment by neerajkhatri-btc** [comment]
@NishantUpadhyay-BTC : ok. i m going to close this
