### ISSUE TITLE
Cover scenario for two same email exists

### ISSUE THREAD

**Issue by NishantUpadhyay-BTC** [NishantUpadhyay-BTC/BLISS-Issue-Tracking#57]
-On the "Breitenbush Account" page, we need to cover the scenario if multiple email matches found. I created two guest ids with the paul@breitenbush.com address and the system just chose the first one. In cases where two or more matches are found, we should display the message "Multiple guest records were found that match this email address. Please call our reservations office at 503.854.3320 to get assistance creating your Breitenbush Account."

**Comment by neerajkhatri-btc** [comment]
@NishantUpadhyay-BTC : this issue is fixed.
