### ISSUE TITLE
Confirmation Process change - Display reservation as unconfirmed

### ISSUE THREAD

**Issue by NishantUpadhyay-BTC** [NishantUpadhyay-BTC/BLISS-Issue-Tracking#58]
-In the Office UI, Reservations made by the Guest UI are showing up as "Confirmed" . These should remain unconfirmed until we send the confirmation letter. Also the UI is sending the confirmation letter, which it shouldn't (I think you know this, but just haven't implemented yet, per my last email) NOTE: these reservations should NOT appear in the "unconfirmed" reservations list on the Home Screen To Do list - just in the Web Reservations list.

**Comment by neerajkhatri-btc** [comment]
@NishantUpadhyay-BTC : this issue is fixed.
