### ISSUE TITLE
Reservation Summary: Need full cost breakdown including Lodging, G.P., Linens, Total, Deposit and Balance Due

### ISSUE THREAD

**Issue by NishantUpadhyay-BTC** [NishantUpadhyay-BTC/BLISS-Issue-Tracking#60]
-Reservation Summary: Need full cost breakdown including Lodging, G.P., Linens, Total, Deposit and Balance Due (see original wireframes from Eric E.). If G.P. or linens were not chosen, then these don't need to be listed here.

**Comment by neerajkhatri-btc** [comment]
@NishantUpadhyay-BTC : this issue is fixed.
