### ISSUE TITLE
Cancellation policy change text in different case

### ISSUE THREAD

**Issue by NishantUpadhyay-BTC** [NishantUpadhyay-BTC/BLISS-Issue-Tracking#61]
-Cancellation Policy: Is it possible for us to have a separate cancellation policy message if the reservation is within 7 days from today? This would be: "Your deposit of $XXX is a non-refundable deposit. Because your reservation is within our 7 day cancellation period, if you have to cancel this reservation your deposit will be forfeited (but do call us right away if an emergency comes up). Your balance of $XXX will be due on arrival. We accept cash, checks (including travelers' checks), Visa, MC and Discover." If not possible or too complex to create a separate policy, then let us know and we'll create one text that covers both cases.

**Comment by neerajkhatri-btc** [comment]
@NishantUpadhyay-BTC : this issue is fixed.
