### ISSUE TITLE
Wrong calculation of balance Due amount

### ISSUE THREAD

**Issue by NishantUpadhyay-BTC** [NishantUpadhyay-BTC/BLISS-Issue-Tracking#62]
-Current Cancellation policy message: balance due is not being calculated correctly. Looks like maybe it's putting in the deposit amount?

**Comment by NishantUpadhyay-BTC** [comment]
In current implementation we are displaying deposit amount. Can you please tell me what is the expected value in following cancallation policy.

For deposit only: "Your deposit of $XXX is a non refundable deposit. If you have to cancel and you give at least 7 days notice, you will be given a Breitenbush credit voucher(minus a $20 processing fee) that is good for one year. If you cancel with less than 7 days notice, your deposit will be forfeited(but do call us right away if an emergency  comes up). Your balance of $%{deposit_amount} will be due on arrival. We accept Cash, Check(including travelers checks), Visa, MC and Discover."

For full payment: "Thank you for paying in full. The first night's stay of $XXX is a non refundable deposit. If you cancel and you give at least 7 days notice, You will be given a Breitenbush credit voucher (minus a $20 processing fee) that is good for one year. If you cancel with less than 7 days notice, your deposit will be forfeited(but do call us right away if an emergency comes up)."

What should be the value of 'XXXX'?

**Comment by neerajkhatri-btc** [comment]
@NishantUpadhyay-BTC : This issue is fixed.
