### ISSUE TITLE
Remove temporary reservation automatically after some time.

### ISSUE THREAD

**Issue by NishantUpadhyay-BTC** [NishantUpadhyay-BTC/BLISS-Issue-Tracking#63]
I'm seeing many temp reservations in the temp reservations list. Shouldn't the system be deleting these after a certain amount of time?

**Comment by HirenBhalani** [comment]
I think we are showing web temp reservations for that.

**Comment by NishantUpadhyay-BTC** [comment]
@neerajkhatri-btc  This issue is no longer exists. Fixed and deployed. So we can close this now.

**Comment by neerajkhatri-btc** [comment]
@NishantUpadhyay-BTC : i m closing this as per your comment
