### ISSUE TITLE
unable to work Reservation>Details>Guest Contact Information>Radio button in office UI

### ISSUE THREAD

**Issue by neerajkhatri-btc** [NishantUpadhyay-BTC/BLISS-Issue-Tracking#7]
pls check that issue

**Comment by NishantUpadhyay-BTC** [comment]
It seems like this is an old issue and it is fixed. @neerajkhatri-btc  Please either reproduce it or close it.

**Comment by neerajkhatri-btc** [comment]
@NishantUpadhyay-BTC : this issue is fixed.
