### ISSUE TITLE
login issue

### ISSUE THREAD

**Issue by neerajkhatri-btc** [NishantUpadhyay-BTC/BLISS-Issue-Tracking#71]
Step 1. continue to booking without entering id and password
Step 2. enter data in Personal Retreat Availability
Step 3. reserve available lodging  
![selection_121](https://cloud.githubusercontent.com/assets/16792762/13492601/019b0bbc-e15f-11e5-901f-eea0d3c43aee.png)

**Comment by neerajkhatri-btc** [comment]
@NishantUpadhyay-BTC : why should display two login forms in same page?

**Comment by NishantUpadhyay-BTC** [comment]
@neerajkhatri-btc We are not sure about the footer till now for login page. I am going to ask question for this so please close this for now.

**Comment by neerajkhatri-btc** [comment]
@NishantUpadhyay-BTC : as per your comment so i close it.
