### ISSUE TITLE
Guest UI: Reservation Summary: Cost Summary Format Incorrect

### ISSUE THREAD

**Issue by NishantUpadhyay-BTC** [NishantUpadhyay-BTC/BLISS-Issue-Tracking#72]
Please see Eric Ellis' hand-drawn wireframe for the correct format for these.

**Comment by neerajkhatri-btc** [comment]
@HirenBhalani-BTC : Please include "On Arrival" in "Balance Due" like("Balance Due On Arrival").
![selection_126](https://cloud.githubusercontent.com/assets/16792762/13592590/872102d8-e519-11e5-9d2d-3a72f77f5ed3.png)

**Comment by neerajkhatri-btc** [comment]
@HirenBhalani-BTC : Wrong Tool Tip in Balance Due. It should be "Balance Due On Arrival"
![selection_128](https://cloud.githubusercontent.com/assets/16792762/13592760/4c7ae804-e51b-11e5-9e74-6264288108c0.png)

**Comment by neerajkhatri-btc** [comment]
@NishantUpadhyay-BTC : this issue is fixed.
