### ISSUE TITLE
Guest UI: Agreements: Preserve checked state on error 

### ISSUE THREAD

**Issue by NishantUpadhyay-BTC** [NishantUpadhyay-BTC/BLISS-Issue-Tracking#73]
If a user misses checking any of the Agreements and tries to continue, the error message displays. When cleared, all agreements return to an unchecked state. Instead, the checked state should be retained. If possible, it would be nice to also highlight (yellow) any boxes that they missed.

**Comment by neerajkhatri-btc** [comment]
@NishantUpadhyay-BTC : this issue is fixed.

**Comment by NishantUpadhyay-BTC** [comment]
@HirenBhalani-BTC  

Here is the log for error on console.

```
ActionController::RoutingError (No route matches [GET] "/guests/check_details"):
  actionpack (4.2.5.1) lib/action_dispatch/middleware/debug_exceptions.rb:21:in `call'
  actionpack (4.2.5.1) lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
  railties (4.2.5.1) lib/rails/rack/logger.rb:38:in `call_app'
  railties (4.2.5.1) lib/rails/rack/logger.rb:20:in `block in call'
  activesupport (4.2.5.1) lib/active_support/tagged_logging.rb:68:in `block in tagged'
  activesupport (4.2.5.1) lib/active_support/tagged_logging.rb:26:in `tagged'
  activesupport (4.2.5.1) lib/active_support/tagged_logging.rb:68:in `tagged'
  railties (4.2.5.1) lib/rails/rack/logger.rb:20:in `call'
  actionpack (4.2.5.1) lib/action_dispatch/middleware/request_id.rb:21:in `call'
  rack (1.6.4) lib/rack/methodoverride.rb:22:in `call'
```

**Comment by neerajkhatri-btc** [comment]
@HirenBhalani-BTC :
![selection_129](https://cloud.githubusercontent.com/assets/16792762/13593001/6ba74e14-e51d-11e5-90bb-b57917bee86e.png)

**Comment by HirenBhalani** [comment]
Not able to reproduce

**Comment by neerajkhatri-btc** [comment]
@NishantUpadhyay-BTC : 
Step 1: Select first and last checkboxes and click agree and continue.
Step 2: unchecked  first and last agreements and click agree and continue.
Step 3: Select all checkboxes and click agree and continue.
![selection_131](https://cloud.githubusercontent.com/assets/16792762/13594543/3d1518c0-e52b-11e5-82d5-833111ca1bc4.png)

**Comment by neerajkhatri-btc** [comment]
@NishantUpadhyay-BTC : this issue is fixed.
