### ISSUE TITLE
Guest UI: Availability: Availability Table: Static Headers

### ISSUE THREAD

**Issue by NishantUpadhyay-BTC** [NishantUpadhyay-BTC/BLISS-Issue-Tracking#75]
The headers of the Availability table (lodging types) should be static - should not scroll with the dates.

**Comment by neerajkhatri-btc** [comment]
@NishantUpadhyay-BTC : UI issue in Availability: Availability Table
![selection_144](https://cloud.githubusercontent.com/assets/16792762/13660379/839a1752-e6af-11e5-9fc0-ad9f552df398.png)

**Comment by neerajkhatri-btc** [comment]
@NishantUpadhyay-BTC : this issue is fixed.
