### ISSUE TITLE
Guest UI: Confirmation Page: Change text and email address

### ISSUE THREAD

**Issue by NishantUpadhyay-BTC** [NishantUpadhyay-BTC/BLISS-Issue-Tracking#76]
The text and email address being displayed at the bottom of the Confirmation page is incorrect.

The text should read:

"Thank you for your reservation. Once we review your reservation for accuracy, we'll send a confirmation email to <user address>" Please contact our reservations office if you do not hear from us within 24 hours."

Currently the email address displayed is "​sshr@breitenbush.com" regardless of what address the user has input. This should display as the user's email address.

**Comment by neerajkhatri-btc** [comment]
@NishantUpadhyay-BTC : Please put "." 
![selection_130](https://cloud.githubusercontent.com/assets/16792762/13593185/1a02c12c-e51f-11e5-8699-45c638118f52.png)

**Comment by neerajkhatri-btc** [comment]
@NishantUpadhyay-BTC : this issue is fixed.
