### ISSUE TITLE
Guest UI: Cancellation Policy: Incorrect balance due

### ISSUE THREAD

**Issue by NishantUpadhyay-BTC** [NishantUpadhyay-BTC/BLISS-Issue-Tracking#77]
The balance due amount displayed on the Cancellation Policy popup is incorrect. It appears to be displaying the total cost of the reservation instead.

**Comment by NishantUpadhyay-BTC** [comment]
Question added on TRAC

**Comment by neerajkhatri-btc** [comment]
@NishantUpadhyay-BTC : this issue is fixed.
