### ISSUE TITLE
Guest UI: Reservation Summary: Departure Date Incorrect

### ISSUE THREAD

**Issue by NishantUpadhyay-BTC** [NishantUpadhyay-BTC/BLISS-Issue-Tracking#78]
The departure date displayed on the Reservation Summary Page (after agreements, before payment) is displaying incorrectly - one day short (i.e. displaying the last night, not on the day of departure).

**Comment by neerajkhatri-btc** [comment]
@NishantUpadhyay-BTC : this issue is fixed.
