### ISSUE TITLE
Office UI: Temporary Reservations: Reservations not expiring.

### ISSUE THREAD

**Issue by NishantUpadhyay-BTC** [NishantUpadhyay-BTC/BLISS-Issue-Tracking#79]
Temporary reservations should expire (and thus be deleted) when the expiration timer (30 min) runs out. Currently there are several aging reservations here. These should have been deleted after 30 minutes of inactivity.

We need to be careful here, as this should only apply to Web reservations.

Also, I notice that some have the "Delete" button greyed out. Why is this?

**Comment by neerajkhatri-btc** [comment]
@NishantUpadhyay-BTC : In Office UI >Temporary Reservations >phone no is not displayed

**Comment by neerajkhatri-btc** [comment]
@NishantUpadhyay-BTC : In Office UI >Temporary Reservations >phone no is not updated
