### ISSUE TITLE
incorrect tooltip in logout button

### ISSUE THREAD

**Issue by neerajkhatri-btc** [NishantUpadhyay-BTC/BLISS-Issue-Tracking#8]
![selection_56](https://cloud.githubusercontent.com/assets/16792762/13008547/eda3b50c-d1bc-11e5-86be-44e3a9750a67.png)

**Comment by NishantUpadhyay-BTC** [comment]
@neerajkhatri-btc  This issue is fixed and deployed. Please have a look.

**Comment by neerajkhatri-btc** [comment]
@NishantUpadhyay-BTC : This issue is fixed.
