### ISSUE TITLE
Office UI: To Do: Web Reservations: Web reservations in progress should not show up here.

### ISSUE THREAD

**Issue by NishantUpadhyay-BTC** [NishantUpadhyay-BTC/BLISS-Issue-Tracking#80]
The "Web Reservations" area of the Office UI should only display reservations made via the Guest UI which have been completed by the guest (paid), but which are not yet confirmed. Currently all reservations in progress are showing up here.

**Comment by neerajkhatri-btc** [comment]
@NishantUpadhyay-BTC : this issue is fixed.
