### ISSUE TITLE
Guest UI: General Design: Footer not always displaying

### ISSUE THREAD

**Issue by NishantUpadhyay-BTC** [NishantUpadhyay-BTC/BLISS-Issue-Tracking#83]
We were running tests and noticed that the footer does not always display. We noticed this on the first page. It was displaying for me (using Chromium) but not Eric - (using Firefox).

**Comment by NishantUpadhyay-BTC** [comment]
We have added question on TRAC for this issue. Until client reply,let's put this on hold.

**Comment by neerajkhatri-btc** [comment]
@NishantUpadhyay-BTC : this issue is fixed.
