### ISSUE TITLE
Guest UI: Availability Page: Change Booking Button

### ISSUE THREAD

**Issue by NishantUpadhyay-BTC** [NishantUpadhyay-BTC/BLISS-Issue-Tracking#84]
Please make the following changes to the "Continue to Booking" button:

-Change button text to: Continue to Make a Reservation

-Adjust color (see ticket #1226)

-Relocate to a position to the right of the color key (just to the right of "Occupied") - space evenly with the color boxes and re-center all three.

**Comment by neerajkhatri-btc** [comment]
@NishantUpadhyay-BTC : this issue is fixed.
