### ISSUE TITLE
Guest UI: Availability: Availability Table unreadable in Mobile

### ISSUE THREAD

**Issue by NishantUpadhyay-BTC** [NishantUpadhyay-BTC/BLISS-Issue-Tracking#85]
The availability table is not readable on a mobile (we tried using iPhone). Words are squished.

Two ideas for fixing this:
one- use abbreviations for Day names (Mon, Tue, Wed, Thu, Fri, Sat, Sun) and also change date format to MM-DD-YY (instead of YYYY).

Second: if needed, we could split this table into two tabs, one for "Cabins" (Bath Cabin, Non-Bath Cabin, Lodge Room) and one for "Camping" (Breitenbush Tent, Your Tent, Personal Vehicle Site) - much like we do on the home screen of the Office UI.

**Comment by neerajkhatri-btc** [comment]
@NishantUpadhyay-BTC : this issue is fixed.
