### ISSUE TITLE
Guest UI: Availability Page: Change Text

### ISSUE THREAD

**Issue by NishantUpadhyay-BTC** [NishantUpadhyay-BTC/BLISS-Issue-Tracking#86]
Please change the paragraph that begins: "Here you can check for general availability… "to "Here is general availability for the next six months. Click on the button below to begin making a reservation".

This text should be centered horizontally, and should split the vertical distance between the color key and the page title.

**Comment by neerajkhatri-btc** [comment]
@NishantUpadhyay-BTC : This issue is fixed.
