### ISSUE TITLE
Guest UI: General Design: Header - remove "Make a Reservation" and "New to Breitenbush" buttons

### ISSUE THREAD

**Issue by NishantUpadhyay-BTC** [NishantUpadhyay-BTC/BLISS-Issue-Tracking#88]
Please remove the "Make a Reservation" and "New to Breitenbush" buttons and replace these with a button labeled "Return to Home Page" - which should return users to the Breitenbush Home Page.

**Comment by neerajkhatri-btc** [comment]
@NishantUpadhyay-BTC : this issue is fixed.
