### ISSUE TITLE
unable to get flash message without entering Arrival Date in Personal Retreat Availability page.

### ISSUE THREAD

**Issue by neerajkhatri-btc** [NishantUpadhyay-BTC/BLISS-Issue-Tracking#9]
1. enter Number Of Nights
2. enter Of Guests (including children)
3. enter minimum number of beds and click check availability

**Comment by NishantUpadhyay-BTC** [comment]
@neerajkhatri-btc This is fixed, Please have a look.

**Comment by neerajkhatri-btc** [comment]
@NishantUpadhyay-BTC : This is fixed.
