### ISSUE TITLE
UI issue in guest info. and payment summary 

### ISSUE THREAD

**Issue by neerajkhatri-btc** [NishantUpadhyay-BTC/BLISS-Issue-Tracking#92]
Step 1. In guest info. First Name and Last name must be center full text in "Individual"
Step 2. special duet in check box is must be center
Step 3. In payment summary expiration in full text "Please Select"
![selection_135](https://cloud.githubusercontent.com/assets/16792762/13626826/6f983118-e5eb-11e5-8d84-8212796dcd4f.png)
![selection_136](https://cloud.githubusercontent.com/assets/16792762/13626352/16d4f8a8-e5e7-11e5-8fa5-4614636ae9f9.png)

**Comment by HirenBhalani-BTC** [comment]
@ni
